src/functionalTest/resources/templates/minimal-appeal-submitted.json
legalRepresentativeName updated to "A Legal Rep" as per AAT test user data
=> updated test data: legalRepresentativeName changed to be in line with AAT

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized
=> RIA-365 notify case officers of submitted appeal

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, infrastructure/main.tf, src/functionalTest/resources/scenarios/RIA-365-send-appeal-submitted-notification-to-manchester.json, src/functionalTest/resources/scenarios/RIA-365-send-appeal-submitted-notification-to-taylor-house.json, src/functionalTest/resources/scenarios/RIA-610-send-build-case-direction-notification.json, src/functionalTest/resources/scenarios/RIA-893-send-home-office-evidence-direction.json, src/functionalTest/resources/templates/minimal-appeal-submitted.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProviderTest.java, src/integrationTest/resources/application-integration.yaml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/AppealSubmittedCaseOfficerNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/StringProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProvider.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifierTest.java
https://tools.hmcts.net/jira/browse/RIA-893
=> RIA-893 Send Home Office evidence direction

src/functionalTest/resources/scenarios/RIA-837-send-legal-rep-review-direction.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/AppealSubmittedCaseOfficerNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeReviewDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifier.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/BuildCaseDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeReviewDirectionNotifierTest.java
Replacement for:
https://github.com/hmcts/ia-case-notifications-api/pull/29
Which has issues on Jenkins...
=> RIA-837 Send legal rep review notification

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, infrastructure/main.tf, src/functionalTest/resources/scenarios/RIA-722-send-respondent-review-direction-manchester.json, src/functionalTest/resources/scenarios/RIA-722-send-respondent-review-direction-taylor-house.json, src/integrationTest/resources/application-integration.yaml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentReviewDirectionNotifier.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentReviewDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/RespondentDirectionPersonalisationFactoryTest.java
https://tools.hmcts.net/jira/browse/RIA-722
Send the "respondent review direction" to the respondent as a notification.
```
[ ] Yes
[X] No
```
=> RIA-722 send respondent review

src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/MapFieldAssertor.java, src/functionalTest/resources/scenarios/RIA-842-send-hearing-requirements-direction.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/AppealSubmittedCaseOfficerNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/BuildCaseDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeHearingRequirementsDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeReviewDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentNonStandardDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentReviewDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerPersonalisationFactory.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativePersonalisationFactory.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/RespondentDirectionPersonalisationFactory.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/AppealSubmittedCaseOfficerNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/BuildCaseDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeHearingRequirementsDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeReviewDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentNonStandardDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentReviewDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerPersonalisationFactoryTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativePersonalisationFactoryTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/RespondentDirectionPersonalisationFactoryTest.java
https://tools.hmcts.net/jira/browse/RIA-842
Send the hearing requirements direction to legal rep.
```
[ ] Yes
[X] No
```
=> RIA-842 Send legal rep hearing requirements direction

config/owasp/suppressions.xml
This is to supress CVE-2019-3795
```
[ ] Yes
[x] No
```
=> Adding suppression of CVE-2019-3795 as does not affect our code.

build.gradle, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java
https://tools.hmcts.net/jira/browse/RIA-941
See Jira
```
[ ] Yes
[x] No
```
=> RIA-941 Generate hearing ready bundle

build.gradle, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java
Bumping jackson version to 2.9.9
```
[ ] Yes
[x] No
```
=> Ria 941 generate hearing ready bundle

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCase.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseBuilder.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseTest.java
=> Ria 574 start desicions and reasons

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PreSubmitCallbackDispatcher.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PreSubmitCallbackDispatcherTest.java
[RIA-1539](https://tools.hmcts.net/jira/browse/RIA-1539)
pre-submit dispatcher handlers ordering for being consistent with ia-case-api:
https://github.com/hmcts/ia-case-api/pull/104
```
[ ] Yes
[x] No
```
=> RIA-1539 pre-submit dispatcher handlers sorting

Jenkinsfile_CNP, build.gradle
[RIA-1640](https://tools.hmcts.net/jira/browse/RIA-1640)
exclude test configurations + fix security vulnerabilities
```
[ ] Yes
[x] No
```
=> RIA-1640 exclude test confs + fix security vulnerabilities

Jenkinsfile_CNP, charts/ia-case-notifications-api/values.yaml
https://tools.hmcts.net/jira/browse/RIA-1653
Updating Helm charts to use new image registry
```
[ ] Yes
[x] No
```
=> RIA-1653 updating image url

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle
Removing deprecated pipeline code
```
[ ] Yes
[ ] No
```
=> removing deprecated features

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/CcdScenarioRunnerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/AuthorizationHeadersProvider.java, src/functionalTest/resources/scenarios/RIA-1610-case-listed-notification-to-manchester.json, src/functionalTest/resources/scenarios/RIA-1610-case-listed-notification-to-taylor-house.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProviderTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseOfficerCaseListedNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerPersonalisationFactory.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseOfficerCaseListedNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerPersonalisationFactoryTest.java
[RIA-1610](https://tools.hmcts.net/jira/browse/RIA-1610)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-1610 notify case officer

build.gradle, src/functionalTest/resources/scenarios/RIA-1610-case-listed-notification-to-manchester.json, src/functionalTest/resources/scenarios/RIA-1610-case-listed-notification-to-taylor-house.json, src/functionalTest/resources/scenarios/RIA-437-case-listed-notification-to-legal-rep-manchester.json, src/functionalTest/resources/scenarios/RIA-437-case-listed-notification-to-legal-rep-taylor-house.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseEmailNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseListedNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseOfficerCaseListedNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeCaseListedNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerPersonalisationFactory.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativePersonalisationFactory.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/DateTimeExtractor.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseListedNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/CaseOfficerCaseListedNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeCaseListedNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerPersonalisationFactoryTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativePersonalisationFactoryTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/DateTimeExtractorTest.java
[RIA-437](https://tools.hmcts.net/jira/browse/RIA-437)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 437 notify legal representative

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/values.yaml, infrastructure/main.tf, src/functionalTest/resources/scenarios/RIA-1647-end-appeal-home-office-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/EndAppealHomeOfficeNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/EndAppealHomeOfficePersonalisationFactory.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/EndAppealHomeOfficeNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/EndAppealHomeOfficePersonalisationFactoryTest.java
[RIA-1647](https://tools.hmcts.net/jira/browse/RIA-1647)
end appeal notify ho
```
[ ] Yes
[x] No
```
=> Ria 1647 end appeal notify ho

build.gradle, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCase.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/serialization/AsylumCaseCallbackDeserializerTest.java
[RIA-1654](https://tools.hmcts.net/jira/browse/RIA-1654)
admin edit listing - changes are needed after notification for edit listing are implemented RIA-1616
```
[ ] Yes
[x] No
```
=> RIA-1654 admin edit listing

zap-known-issues.xml
[RIA-1643](https://tools.hmcts.net/jira/browse/RIA-1643)
zap alerts
please refer to the comment in PR https://github.com/hmcts/ia-case-api/pull/139
```
[ ] Yes
[ ] No
```
=> zap alerts

build.gradle
N/A
security vulnerabilities fix
```
[ ] Yes
[x] No
```
=> security vulnerabilities fix

Dockerfile, build.gradle
=> Updating app insights agent jar

Jenkinsfile_CNP
To enable AKS in AAT for notifications api.
=> enable aks in aat for notifications-api

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java
N/A
add missing DocumentTag values
```
[ ] Yes
[x] No
```
=> add missing DocumentTag values

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java
N/A
re-build package and deploy fresh version on AAT and Prod
```
[ ] Yes
[x] No
```
=> re-trigger deployment

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java
N/A
re-trigger build with latest configs
```
[ ] Yes
[x] No
```
=> re-trigger build to refresh package

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/DateProvider.java
N/A
re-trigger build for new flux config
```
[ ] Yes
[ ] No
```
=> re-trigger build for new flux config

src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/CcdScenarioRunnerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/AuthorizationHeadersProvider.java, src/functionalTest/resources/scenarios/RIA-1792-notify-case-officer-of-respondent-evidence-submitted.json, src/functionalTest/resources/scenarios/RIA-1793-ho-generic-uploaded-response.json, src/functionalTest/resources/scenarios/RIA-1793-ho-lart-uploaded-response.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerHomeOfficeResponseUploadedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerHomeOfficeResponseUploadedPersonalisationTest.java
[RIA-1793](https://tools.hmcts.net/jira/browse/RIA-1793)
case officer notification for ho uploaded response
```
[ ] Yes
[x] No
```
=> RIA-1793 home office response uploaded

src/functionalTest/resources/scenarios/RIA-1794-request-response-review.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeRequestResponseReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeRequestResponseReviewPersonalisationTest.java
[RIA-1794](https://tools.hmcts.net/jira/browse/RIA-1794)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 1794 ho response under review

charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.aat.template.yaml, charts/ia-case-notifications-api/values.preview.template.yaml, charts/ia-case-notifications-api/values.yaml, web.config
Fixing up repo after AKS migration
=> Fixing up project after AKS migration

src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-bradford.json, src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-taylor-house.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-1024
Case submitted notification to case officer
```
[ ] Yes
[X] No
```
=> Ria 1024 notify co of case built

src/functionalTest/resources/scenarios/RIA-942-hearing-bundle-is-ready-notification-to-home-office.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerRespondentEvidenceSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/HomeOfficeHearingBundleReadyPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeHearingBundleReadyPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/GovNotifyTemplateIdConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerRespondentEvidenceSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/CaseOfficerSubmitCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/HomeOfficeHearingBundleReadyPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeHearingBundleReadyPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
[RIA-942](https://tools.hmcts.net/jira/browse/RIA-942)
Notify homeOffice and legal rep of hearing bundle is ready
```
[ ] Yes
[x] No
```
=> RIA-942 notify homeOffice and legaRep of hearing bundle is ready

src/functionalTest/resources/scenarios/RIA-1191-non-standard-direction-hearing-requirements.json, src/functionalTest/resources/scenarios/RIA-414-RIA-1191-send-home-office-non-standard-direction.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/SendsDirectionTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeNonStandardDirectionOfHomeOfficePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeNonStandardDirectionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/BasePersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/GovNotifyTemplateIdConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeNonStandardDirectionOfHomeOfficePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LegalRepresentativeNonStandardDirectionPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/BasePersonalisationProviderTest.java
[RIA-1191](https://tools.hmcts.net/jira/browse/RIA-1191)
Notification on all non-standard directions
```
[ ] Yes
[x] No
```
=> RIA-1191 notification on all non standard directions

src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-bradford.json, src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-taylor-house.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-birmingham.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-glasgow.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-hatton-cross.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-north-shields.json
Correcting a typo change on the notifications templates, this is change was done on the gov notify templates.
```
[ ] Yes
[x ] No
```
=> Correcting a typo change on the notifications templates

src/functionalTest/resources/scenarios/RIA-1966-aip-send-appeal-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-2047-direction-request-hearing-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRequestHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/GovNotifyTemplateIdConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRequestHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAddAppealPersonalisationTest.java
[RIA-2047](https://tools.hmcts.net/jira/browse/RIA-2047)
Direction to legal rep to submit hearing requirements
```
[ ] Yes
[x] No
```
=> RIA-2047 send direction to legal rep to submit hearing requirements

src/functionalTest/resources/scenarios/RIA-1283-notification-of-submitted-hearing-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmittedHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeSubmittedHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/BasePersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/GovNotifyTemplateIdConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmittedHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeSubmittedHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/BasePersonalisationProviderTest.java
[RIA-1283](https://tools.hmcts.net/jira/browse/RIA-1283)
Notification of submitted hearing requirements
```
[ ] Yes
[x] No
```
=> RIA-1283 notification of submitted hearing requirements

src/functionalTest/resources/scenarios/RIA-2047-direction-request-hearing-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/LegalRepresentativeRequestHearingRequirementsPersonalisationTest.java
N/A
fix functional tests when flag "submit hearing requirements" is enabled
```
[ ] Yes
[x] No
```
=> fix functional tests when flag "submit hearing requirements" is enabled

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/values.yaml, infrastructure/main.tf, src/functionalTest/resources/scenarios/RIA-2168-hearing-requirements-adjustment-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReviewHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application-email-addresses.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReviewHearingRequirementsPersonalisationTest.java
[RIA-2168](https://tools.hmcts.net/jira/browse/RIA-2168)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-2168 hearing requirements adjustment notification

infrastructure/main.tf
N/A
fix terraform script
```
[ ] Yes
[x] No
```
=> fix terraform script

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/SendsDirectionTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/Direction.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/PreviousDates.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/PreviousDatesTest.java
[RIA-723](https://tools.hmcts.net/jira/browse/RIA-723)
edit direction due date
```
[ ] Yes
[x] No
```
=> RIA-723 edit direction date

build.gradle, infrastructure/ithc.tfvars, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/SmsNotificationGenerator.java
N/A
AKS migration for ITHC env
```
[ ] Yes
[x] No
```
=> ithc aks migration

src/functionalTest/resources/scenarios/RIA-1966-aip-send-appeal-submitted-notifications-to-appellant.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/DateProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/SystemDateProvider.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/SystemDateProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-1966
Updated Notification: Appeal submitted (AiP) template to match new version.
Updated unit tests and functional tests
```
[ ] Yes
[x ] No
```
=> RIA-1966: Template Update

src/functionalTest/resources/scenarios/RIA-1966-aip-send-appeal-submitted-notifications-to-appellant.json
https://tools.hmcts.net/jira/browse/RIA-1966
Update word on subject template.
```
[ ] Yes
[x ] No
```
=> RIA-1966-patch: Update subject

charts/ia-case-notifications-api/Chart.yaml, src/main/resources/application-email-addresses.yaml
Fix to ensure default email address are not used but rather pulled correctly from the vault. 
[RIA-2366](https://tools.hmcts.net/jira/browse/RIA-2366)
See Jira
```
[ ] Yes
[x] No
```
=> chart upgrade after change to values.yaml

src/functionalTest/resources/scenarios/RIA-1966-aip-send-appeal-submitted-notifications-to-appellant.json
RIA-1966
```
[ ] Yes
[ x] No
```
=> Updates content changes.

src/functionalTest/resources/scenarios/RIA-2169-without-hearing-requirements-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerWithoutHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/BasePersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerWithoutHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/BasePersonalisationProviderTest.java
[RIA-2169](https://tools.hmcts.net/jira/browse/RIA-2169)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-2169 hearing requirements submitted notification

charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml
N/A
app insights key
```
[ ] Yes
[x] No
```
=> app insights key

src/main/resources/bootstrap.yaml
adding `AppInsightsInstrumentationKey`
=> Adding missing appinsights into bootstrap mapping.

src/functionalTest/resources/scenarios/RIA-2405-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/templates/aip-minimal-appeal-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/NotificationType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealOutOfTimePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealOutOfTimePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/RecipientsFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealOutOfTimePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealOutOfTimePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/RecipientsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-2405
- Adds Submission Out of time  Notifications Email & Text for AIP Journeys based on sumissionOutOTime field.
- Adds unit tests 
- Adds functional tests
- Also adds a Recipient Finder to avoid duplication
```
[ ] Yes
[ x] No
```
=> RIA-2405 - 

src/functionalTest/resources/scenarios/RIA-2345-legalrep-notification-of-change-direction-due-date.json, src/functionalTest/resources/scenarios/RIA-2345-respondent-notification-of-change-direction-due-date-after-respondent-review.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDateOfHomeOfficePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentChangeDirectionDueDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/GovNotifyTemplateIdConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDateOfHomeOfficePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentChangeDirectionDueDatePersonalisationTest.java
[RIA-2345](https://tools.hmcts.net/jira/browse/RIA-2345)
Notification of change direction due date
```
[ ] Yes
[x] No
```
=> RIA-2345 notification of change due date

build.gradle, src/functionalTest/resources/scenarios/RIA-2550-aip-send-request-respondent-evidence-notifications-to-appellant.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestRespondentEvidencePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestRespondentEvidencePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestRespondentEvidencePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestRespondentEvidencePersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-2550
**RIA-2550:** 
- Adds Appellant notifications when TCW requests the Home Office to upload their bundle.
- Added Functional and unit tests.
```
[ ] Yes
[x ] No
```
=> RIA-2550: AiP Appellant Home Office bundle notification

src/functionalTest/resources/scenarios/RIA-2345-legalrep-notification-of-change-direction-due-date.json, src/functionalTest/resources/scenarios/RIA-2345-respondent-notification-of-change-direction-due-date-after-respondent-review.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/GovNotifyTemplateIdConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
RIA-2345(https://tools.hmcts.net/jira/browse/RIA-2345)
Notification of change direction due date refactor
```
[ ] Yes
[x] No
```
=> RIA-2345 notification of change direction due date refactor

charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml
=> removing aadidentityname

charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/controllers/PreSubmitCallbackController.java
N/A
revert aadIdentityName refactor
```
[ ] Yes
[ ] No
```
=> revert aadIdentityName refactor

charts/ia-case-notifications-api/values.preview.template.yaml
N/A
remove deprecation
```
[ ] Yes
[x] No
```
=> remove deprecation

security.sh
N/A
zap testing report in HTML
```
[ ] Yes
[x] No
```
=> zap testing report in HTML

src/functionalTest/resources/scenarios/RIA-1380-edit-case-listing-notification-bradford-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1380-edit-case-listing-notification-newport-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1616-admin-office-edit-case-listing-notification-bradford-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-birmingham-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-glasgow-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-hatton-cross-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-north-shields-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-2297-edit-listing-notification-to-admin-team.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerChangeToHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerPersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReviewHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerChangeToHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerPersonalisationProviderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerWithoutHearingRequirementsPersonalisationTest.java
[RIA-2297](https://tools.hmcts.net/jira/browse/RIA-2297)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-2297 edit listing notification to admin team

build.gradle
dependency check fix for CVE-2020-1938
```
[ ] Yes
[X] No
```
=> dependency check fix for CVE-2020-1938

src/functionalTest/resources/scenarios/RIA-1966-aip-send-appeal-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-2270-aip-reason-for-appeal submitted.json, src/functionalTest/resources/scenarios/RIA-2405-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealOutOfTimePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitReasonsForAppealPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealOutOfTimePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitReasonsForAppealPersonalisationSms.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealOutOfTimePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitReasonsForAppealPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantReasonsForAppealSubmittedPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealOutOfTimePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/SystemDateProviderTest.java
Updated copy in notify for when a TCW needs to reply by. This meant the
tests need updating. Also the dueDate value needed extending to 4 weeks
from 2.
https://tools.hmcts.net/jira/browse/RIA-2642
=> RIA-2642 TCW deadlines

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/CcdScenarioRunnerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/AuthorizationHeadersProvider.java, src/functionalTest/resources/scenarios/RIA-2239-end-appeal-home-office-notification-judge.json, src/main/resources/application.yaml
[RIA-2239](https://tools.hmcts.net/jira/browse/RIA-2239)
Functionality added to allow a judge to end appeal
```
[ ] Yes
[X] No
```
=> RIA-2239 judge endAppeal

src/functionalTest/resources/scenarios/RIA-2240-legalrep-notification-of-change-direction-due-date.json, src/functionalTest/resources/scenarios/RIA-2240-respondent-notification-of-change-direction-due-date-after-respondent-review.json, src/main/resources/application.yaml
[RIA-2240](https://tools.hmcts.net/jira/browse/RIA-2240)
```
[ ] Yes
[X] No
```
=> Ria 2240 due date judge

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/HealthCheckConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/health/DownStreamHealthIndicator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/health/ServiceHealthIndicator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/health/DownStreamHealthIndicatorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/health/ServiceHealthIndicatorTest.java
[RIA-2526](https://tools.hmcts.net/jira/browse/RIA-2526)
Notification api downstream services health check
```
[ ] Yes
[x] No
```
=> RIA-2526 downstream services health check

src/smokeTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/SmokeTest.java
[RIA-1906](https://tools.hmcts.net/jira/browse/RIA-2196)
Smoke test improvement
```
[ ] Yes
[x] No
```
=> RIA-1906 health smoke test

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/controllers/advice/AsylumCaseRequestAdapter.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/controllers/advice/CallbackControllerAdvice.java
[RIA-2646](https://tools.hmcts.net/jira/browse/RIA-2646)
Case details logging when there is an exception
```
[ ] Yes
[x] No
```
=> RIA-2646 log ccd id on exceptions

src/functionalTest/resources/scenarios/RIA-1400-appeal-exited-online-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-1400-appeal-exited-online-before-listing-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeAppealExitedOnlinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealExitedOnlinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeAppealExitedOnlinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealExitedOnlinePersonalisationTest.java
[RIA-1400](https://tools.hmcts.net/jira/browse/RIA-1400)
```
[ ] Yes
[X] No
```
=> RIA-1400 appeal exited online notification

src/functionalTest/resources/scenarios/RIA-2644-send-change-hearing-centre-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeHearingCentrePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeHearingCentrePersonalisationTest.java
[RIA-2644: Change designated hearing centre](https://tools.hmcts.net/jira/browse/RIA-2644)
Created a legal representative personalisation email to send to legal rep on the event of `CHANGE_HEARING_CENTRE`.
```
[ ] Yes
[x] No
```
=> RIA-2644: Change of designated hearing centre

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, infrastructure/main.tf, src/functionalTest/resources/scenarios/RIA-1373-notification-of-appellant-ftpa-submitted.json, src/functionalTest/resources/scenarios/RIA-1373-notification-of-respondent-ftpa-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRespondentFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAppellantFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerFtpaSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeFtpaSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRespondentFtpaSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAppellantFtpaSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentFtpaSubmittedPersonalisationTest.java
[RIA-1373](https://tools.hmcts.net/jira/browse/RIA-1373)
Notification of FTPA application submitted.
```
[ ] Yes
[x] No
```
=> RIA-1373 notification of ftpa application submitted

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RIA-2821
RIA-2821 urls out of vault
```
[ ] Yes
[X] No
```
=> RIA-2821 urls out of vault

src/main/resources/application.yaml
N/A
fix vault breakout with new values
```
[ ] Yes
[x] No
```
=> fix vault breakout with new values

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ClarifyingQuestion.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/Direction.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ClarifyingQuestionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTest.java
Added new domain objects for clarifying questions.
```
[ ] Yes
[ ] No
```
=> RIA-2864-Clarifying_question

Jenkinsfile_CNP, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.aat.template.yaml, charts/ia-case-notifications-api/values.preview.template.yaml, charts/ia-case-notifications-api/values.sandbox.template.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-2799
Updated EXUI Frontend URLs for aat AKS environment rather than ASE
as per: https://tools.hmcts.net/confluence/display/EUI/Expert+UI+Environments
```
[ ] Yes
[x ] No
```
=> Update EXUI Urls to AKS

src/functionalTest/resources/scenarios/RIA-1976-RIA-1898-respondent-review-direction-birmingham.json, src/functionalTest/resources/scenarios/RIA-1976-RIA-1898-respondent-review-direction-glasgow.json, src/functionalTest/resources/scenarios/RIA-1976-RIA-1898-respondent-review-direction-hatton-cross.json, src/functionalTest/resources/scenarios/RIA-1976-RIA-1898-respondent-review-direction-north-shields.json, src/functionalTest/resources/scenarios/RIA-722-RIA-1898-send-respondent-review-direction-manchester.json, src/functionalTest/resources/scenarios/RIA-722-RIA-1898-send-respondent-review-direction-taylor-house.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRespondentReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRespondentReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-1898
- Added a new personalisation for legal representative.
- Updated existing functional tests to test the sending of this notification.
```
[ ] Yes
[x] No
```
=> RIA-1898: Notification to legal representative on request respondent review event

src/main/resources/application.yaml
[RIA-921](https://tools.hmcts.net/jira/browse/RIA-921)
system user access
```
[ ] Yes
[x] No
```
=> RIA-921 system user access

build.gradle, src/functionalTest/resources/scenarios/RIA-739-request-case-edit-legal-representative.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestCaseEditPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestCaseEditPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-739
=> RIA-739 add code to send out new notification

src/functionalTest/resources/scenarios/RIA-2775-force-case-progression-to-case-under-review.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeForceCaseProgressionToCaseUnderReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeForceCaseProgressionToCaseUnderReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2775
- New notifcation handler for force case to case under review event which sends a notification to legal rep.
```
[ ] Yes
[x] No
```
=> RIA-2775: Force case progression to case under review notification.

src/functionalTest/resources/scenarios/RIA-2776-force-case-to-submit-hearing-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentForceCaseToSubmitHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentForceCaseToSubmitHearingRequirementsPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2776
- Sending notification to the respondent (LART) about this event.
```
[ ] Yes
[x] No
```
=> RIA-2776: Force case progression to submit hearing requirements.

src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/AuthorizationHeadersProvider.java
N/A
functional tests auth improvement
```
[ ] Yes
[x] No
```
=> functional tests auth improvement

src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-bradford.json, src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-taylor-house.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-birmingham.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-glasgow.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-hatton-cross.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-north-shields.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeSubmitCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeSubmitCasePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-1281
Moved from other branch as can't merge it
```
[ ] Yes
[x] No
```
=> moved code onto new branch as github branch broken

src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-bradford.json, src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-taylor-house.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-birmingham.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-glasgow.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-hatton-cross.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-north-shields.json, src/functionalTest/resources/scenarios/RIA-2240-RIA-2694-legalrep-notification-of-change-direction-due-date.json, src/functionalTest/resources/scenarios/RIA-2240-RIA-2694-respondent-notification-of-change-direction-due-date-after-respondent-review.json, src/functionalTest/resources/scenarios/RIA-2345-RIA-2694-respondent-notification-of-change-direction-due-date-after-respondent-review.json, src/functionalTest/resources/scenarios/RIA-3228-change-direction-due-date-both-parties.json, src/functionalTest/resources/scenarios/RIA-3228-non-standard-direction-to-both-parties.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDateOfHomeOfficePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentChangeDirectionDueDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDateOfHomeOfficePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeChangeDirectionDueDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentChangeDirectionDueDatePersonalisationTest.java
[RIA-3228](https://tools.hmcts.net/jira/browse/RIA-3328)
Fix for sending a non standard direction to both parties
```
[ ] Yes
[x] No
```
=> RIA-3228 Send a non standard direction to both parties

src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-bradford-save-and-continue-disabled.json, src/functionalTest/resources/scenarios/RIA-1024-case-submitted-notification-to-case-officer-taylor-house-save-and-continue-disabled.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-birmingham-save-and-continue-disabled.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-glasgow-save-and-continue-disabled.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-hatton-cross-save-and-continue-disabled.json, src/functionalTest/resources/scenarios/RIA-1976-case-submitted-notification-to-case-officer-north-shields-save-and-continue-disabled.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
=> RIA-2918 send legal rep notification when submissions

src/functionalTest/resources/scenarios/RIA-2338-send-edit-appeal-after-submit-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-2338-send-edit-appeal-after-submit-before-listing-notification.json, src/functionalTest/resources/scenarios/RIA-2338-send-edit-appeal-after-submit-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditAppealAfterSubmitPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditAppealAfterSubmitPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2338
- Created a new personalisation class for the event.
- Added the new event to Events class.
- Created a notifications handler and generator for this notification.
```
[ ] Yes
[x] No
```
=> RIA-2338: Sending notification to legal rep for editAppealAfterSubmitted event

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/ErrorHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandlerTest.java
N/A
handle errors gracefully
```
[ ] Yes
[x] No
```
=> handle errors gracefully

audit.json
https://tools.hmcts.net/jira/browse/RIA-3420
RIA-3420_Nightly_Build_Fix
```
[ ] Yes
[X] No
```
=> RIA-3420_Nightly_Build_Fix

src/functionalTest/resources/scenarios/RIA-3295-link-appeal-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-3295-link-appeal-before-listing-notification.json, src/functionalTest/resources/scenarios/RIA-3295-unlink-appeal-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-3295-unlink-appeal-before-listing-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ReasonForLinkAppealOptions.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealExitedOnlinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/linkunlinkappeal/LegalRepresentativeLinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/linkunlinkappeal/LegalRepresentativeUnlinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealService.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealExitedOnlinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/linkunlinkappeal/LegalRepresentativeLinkAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/linkunlinkappeal/LegalRepresentativeUnlinkAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-3295
=> RIA-3295 add new linkAppeal and unlinkAppeal events

src/functionalTest/resources/scenarios/RIA-3295-RIA-3329-link-appeal-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-3295-RIA-3329-link-appeal-before-listing-notification.json, src/functionalTest/resources/scenarios/RIA-3295-RIA-3329-unlink-appeal-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-3295-RIA-3329-unlink-appeal-before-listing-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/linkunlinkappeal/HomeOfficeLinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/linkunlinkappeal/HomeOfficeUnlinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/linkunlinkappeal/HomeOfficeLinkAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/linkunlinkappeal/HomeOfficeUnlinkAppealPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-3329
=> RIA-3329 Feature/ria 3329 link unlink ho notification

src/functionalTest/resources/scenarios/RIA-1647-RIA-1276-RIA-2936-end-appeal-home-office-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-2239-RIA-2936-end-appeal-home-office-notification-judge-after-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEndAppealPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEndAppealPersonalisationTest.java
RIA-2535
home office email address fix
```
[ ] Yes
[x] No
```
=> RIA-2535 home office email address fix

src/functionalTest/resources/scenarios/RIA-2783-edit-documents-after-listing.json, src/functionalTest/resources/scenarios/RIA-2783-edit-documents-before-listing.json, src/functionalTest/resources/scenarios/RIA-2783-edit-documents.json, src/functionalTest/resources/scenarios/RIA-3295-unlink-appeal-after-listing-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/editdocument/CaseOfficerEditDocumentsPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/editdocument/CaseOfficerEditDocumentsPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2830
=> fix notification for before listing scenario

.travis.yml, Dockerfile, build.gradle
[RIA-3440](https://tools.hmcts.net/jira/browse/RIA-3440)
```
[x] Yes
[ ] No
```
=> RIA-3440 upgrading to Java11

build.gradle
[RIA-3479](https://tools.hmcts.net/jira/browse/RIA-3479)
```
[ ] Yes
[x] No
```
=> RIA-3479 upgrade pitest verion forjava11

src/functionalTest/resources/scenarios/RIA-2774-force-case-progression-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentForceCaseProgressionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentForceCaseProgressionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2774
=> RIA-2774 fix notification template

infrastructure/state.tf, src/functionalTest/resources/scenarios/RIA-2923-hearing-bundle-failed-notification-to-north-shields.json, src/functionalTest/resources/scenarios/RIA-3116-hearing-bundle-failed-notification-to-north-shields.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHearingBundleFailedPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHearingBundleFailedPersonalisationTest.java
N/A
remove remote state terraform scripts
```
[ ] Yes
[x] No
```
=> remove remote state terraform scripts

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-3372
CVE suppression clean up
```
[ ] Yes
[X] No
```
=> RIA-3372: CVE suppression clean up

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/RIA-2118-send-appeal-submitted-to-home-office.json, src/functionalTest/resources/scenarios/RIA-365-RIA-2936-send-appeal-submitted-notification-to-taylor-house.json, src/integrationTest/resources/application-integration.yaml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeSubmitAppealPersonalisation.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
[RIA-3496](https://tools.hmcts.net/jira/browse/RIA-3496)
Home office APC inbox notification of submit appeal
```
[ ] Yes
[x] No
```
=> RIA-3496 home office apc notification of submit appeal

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/security/RequestUserAccessTokenProvider.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/security/RequestUserAccessTokenProviderTest.java
N/A
fix Sonar checks
```
[ ] Yes
[x] No
```
=> fix Sonar checks

src/functionalTest/resources/scenarios/RIA-429-send-appeal-submitted-and-paid-notification-legal-rep.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPaidPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-429
RIA-429 notify legal REP
```
[ ] Yes
[X] No
```
=> Ria 429 pay submit

src/functionalTest/resources/scenarios/RIA-3366-notification-of-admin-officer-uploaded-addendum-evidence.json, src/functionalTest/resources/scenarios/RIA-414-RIA-1191-RIA-2694-send-home-office-non-standard-direction-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-3366
Added notifications for addendum evidence upload as a Admin officer
```
[ ] Yes
[ x] No
```
=> RIA-3366: UploadAddendumEvidence for Admin Officers

src/functionalTest/resources/scenarios/RIA-3472-send-appeal-submitted-and-paylater-notification-legal-rep.json, src/functionalTest/resources/scenarios/RIA-3472-send-appeal-submitted-dc-appeal-type-notification-legal-rep.json, src/functionalTest/resources/scenarios/RIA-3472-send-appeal-submitted-rp-appeal-type-notification-legal-rep.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayLaterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayLaterPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-3472
Add notification for appeal submitted for RP and DC appeal type or PA appeal type with pay later option
```
[ ] Yes
[ X] No
```
=> Ria 3472 pay later pba

src/functionalTest/resources/scenarios/RIA-3025-paid-notification-legal-rep-after-appeal-submitted-after-listing.json, src/functionalTest/resources/scenarios/RIA-3025-paid-notification-legal-rep-after-appeal-submitted-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePaymentPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePaymentPaidPersonalisationTest.java
[RIA-3025](https://tools.hmcts.net/jira/browse/RIA-3025)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3025 pending payment paid notification (after appealSubmitted)

src/functionalTest/resources/scenarios/RIA-1191-RIA-2694-non-standard-direction-hearing-requirements-after-listing.json, src/functionalTest/resources/scenarios/RIA-1191-RIA-2694-non-standard-direction-hearing-requirements-before-listing.json, src/functionalTest/resources/scenarios/RIA-1674-RIA-2936-record-refused-application-taylor-house-ho-and-legal-rep-notifications-after-listing.json, src/functionalTest/resources/scenarios/RIA-2208-RIA-2694-send-non-standard-direction-judge-after-listing.json, src/functionalTest/resources/scenarios/RIA-2208-RIA-2694-send-non-standard-direction-judge-before-listing.json, src/functionalTest/resources/scenarios/RIA-2240-RIA-2694-legalrep-notification-of-change-direction-due-date.json, src/functionalTest/resources/scenarios/RIA-2240-RIA-2694-respondent-notification-of-change-direction-due-date-after-respondent-review.json, src/functionalTest/resources/scenarios/RIA-2536-adjourn-record-refused-application-taylor-ho-and-legal-rep-notifications-prepare-for-hearing.json, src/functionalTest/resources/scenarios/RIA-2536-expedite-record-refused-application-taylor-ho-and-legal-rep-notifications-prepare-for-hearing.json, src/functionalTest/resources/scenarios/RIA-2536-time-extension-record-refused-application-apc-ho-and-legal-rep-notifications-await-evidence.json, src/functionalTest/resources/scenarios/RIA-2536-time-extension-record-refused-application-lart-ho-and-legal-rep-notifications-case-under-review.json, src/functionalTest/resources/scenarios/RIA-2536-time-extension-record-refused-application-lart-ho-and-legal-rep-notifications-res-review.json, src/functionalTest/resources/scenarios/RIA-2536-transfer-record-refused-application-taylor-ho-and-legal-rep-notifications-prepare-for-hearing.json, src/functionalTest/resources/scenarios/RIA-2536-withdraw-record-refused-application-apc-ho-and-legal-rep-notifications-start.json, src/functionalTest/resources/scenarios/RIA-2536-withdraw-record-refused-application-lart-ho-and-legal-rep-notifications-res-review.json, src/functionalTest/resources/scenarios/RIA-2536-withdraw-record-refused-application-taylor-ho-and-legal-rep-notifications-submit-hearing-reqs.json, src/functionalTest/resources/scenarios/RIA-3228-non-standard-direction-to-both-parties.json, src/functionalTest/resources/scenarios/RIA-414-RIA-1191-RIA-2694-send-home-office-non-standard-direction-after-listing.json, src/functionalTest/resources/scenarios/RIA-414-RIA-1191-RIA-2694-send-home-office-non-standard-direction-before-listing.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRecordApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/RecordApplicationRespondentFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRecordApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2536
```
[ ] Yes
[x] No
```
=> Ria 2536 record app ho notif

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java
[RIA-2536](https://tools.hmcts.net/jira/browse/RIA-2536)
fix for ended and appealTakenOffline state.
```
[ ] Yes
[x] No
```
=> fix for ria-2536 ended and appealTakenOffline state

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
[RIA-3434](https://tools.hmcts.net/jira/browse/RIA-3434)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3434 pay offline by card pa

Jenkinsfile_CNP, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/RIA-3220-send-appeal-submitted-payment-pending-notification-legal-rep.json, src/integrationTest/resources/application-integration.yaml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPayOfflinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayOfflinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPayOfflinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayOfflinePersonalisationTest.java
[RIA-3220](https://tools.hmcts.net/jira/browse/RIA-3220)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3220 Pay offline - Notifications when a PA appeal has been lodged and payment is pending

src/functionalTest/resources/scenarios/RIA-3103-request-response-amend.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentRequestResponseAmendPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentRequestResponseAmendPersonalisationTest.java
[RIA-3103](https://tools.hmcts.net/jira/browse/RIA-3103)
```
[ ] Yes
[x] No
```
=> TAB-3103 Send notification when Request response amend

src/functionalTest/resources/scenarios/RIA-2783-edit-documents-after-listing.json, src/functionalTest/resources/scenarios/RIA-2783-edit-documents-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/editdocument/CaseOfficerEditDocumentsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/editdocument/EditDocumentService.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/editdocument/CaseOfficerEditDocumentsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/editdocument/EditDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-3348
=> RIA-3348 Feature/ria 3348 edit doc improvements

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatus.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatusTest.java
[RIA-3473](https://tools.hmcts.net/jira/browse/RIA-3473)
Mark appeal as paid for the appeal types EA/HU/PA
```
[ ] Yes
[x] No
```
=> RIA-3473 mark appeal as paid of appeal types EA/HU/PA

src/functionalTest/resources/scenarios/RIA-3219-appeal-submitted-paid-notification-after-listing-legal-rep-pa-appeal-type.json, src/functionalTest/resources/scenarios/RIA-3219-appeal-submitted-paid-notification-before-listing-legal-rep-pa-appeal-type.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePendingPaymentPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/linkunlinkappeal/LegalRepresentativeUnlinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatusTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePendingPaymentPaidPersonalisationTest.java
[RIA-3219](https://tools.hmcts.net/jira/browse/RIA-3219)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3219 pending payment paid notification

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatus.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatusTest.java
https://tools.hmcts.net/jira/browse/RIA-3592
RIA-3592_payment_status
```
[ ] Yes
[X] No
```
=> Ria 3592 payment status

src/functionalTest/resources/scenarios/RIA-3492-appeal-submitted-paid-notification-ea-appeal-type.json, src/functionalTest/resources/scenarios/RIA-3492-appeal-submitted-paid-notification-hu-appeal-type.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerPendingPaymentPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePendingPaymentPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerPendingPaymentPaidPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePendingPaymentPaidPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-3492
add notification for pending payment paid for EA and HU appeals
```
[ ] Yes
[X] No
```
=> Ria 3492 notification pending payment paid ea hu

infrastructure/main.tf
RIA-3668
Azure provider upgrade
```
[ ] Yes
[x] No
```
=> Azure provider upgrade

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/Application.java
N/A
MI migration test
```
[ ] Yes
[x] No
```
=> MI migration test

src/main/resources/application.yaml
[RIA-3457](https://tools.hmcts.net/jira/browse/RIA-3457)
CaseOfficer and Judge decide an online application
```
[ ] Yes
[x] No
```
=> RIA-3451 CO and Judge decide an application

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-3155
Adding reinstate access to Case officer
```
[ ] Yes
[X ] No
```
=> Add reinstate for Case Officer taken out after rebase of 3453

src/functionalTest/resources/scenarios/RIA-3453-make-an-application-notification-home-office-pou-hc-before-listing.json, src/functionalTest/resources/scenarios/RIA-3454-decide-an-application-notification-home-office-generic-pou-granted-hc-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
--
Fix POU email before listing for make and decide an application
```
[ ] Yes
[ X] No
```
=> Fix POU case before listing for Make or decide an application

src/functionalTest/resources/scenarios/RIA-3652-direction-request-new-hearing-requirements-case-officer.json, src/functionalTest/resources/scenarios/RIA-3652-direction-request-new-hearing-requirements-judge.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestNewHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestNewHearingRequirementsPersonalisationTest.java
[RIA-3652](https://tools.hmcts.net/jira/browse/RIA-3652)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3652 direction and state change ftpa decision reheard

build.gradle, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ApplicantTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/CaseNoteTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/JourneyTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/SubscriberTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/TimeExtensionDecisionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/TimeExtensionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/YesOrNoTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/em/BundleTest.java
Pitest plugin for Junit5
https://tools.hmcts.net/jira/browse/RIA-3760
```
[ ] Yes
[ x] No
```
=> Pitest plugin for Junit5

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/RIA-1373-RIA-2936-notification-of-appellant-ftpa-submitted.json, src/functionalTest/resources/scenarios/RIA-1373-RIA-2936-notification-of-respondent-ftpa-submitted.json, src/functionalTest/resources/scenarios/RIA-1380-RIA-2936-send-appeal-submitted-notification-to-bradford-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1380-RIA-2936-send-appeal-submitted-notification-to-newport-hearing-centre.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAppellantFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/HomeOfficeFtpaEmailAddressesConfiguration.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAppellantFtpaSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentFtpaSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
[RIA-3742](https://tools.hmcts.net/jira/browse/RIA-3742)
```
[ ] Yes
[x] No
```
=> RIA-3742 notify homeoffice ftpa-appalent-summitted

src/functionalTest/resources/scenarios/RIA-3582-hearing-requirements-adjustment-submitted-flag-missing.json, src/functionalTest/resources/scenarios/RIA-3582-hearing-requirements-adjustment-submitted-flag-no.json, src/functionalTest/resources/scenarios/RIA-3582-hearing-requirements-adjustment-submitted-ftpa-reheard.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReviewHearingRequirementsPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReviewHearingRequirementsPersonalisationTest.java
[RIA-3582](https://tools.hmcts.net/jira/browse/RIA-3582)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3582 tcw review requirements

src/functionalTest/resources/scenarios/RIA-3386-without-hearing-requirements-submitted-flag-missing.json, src/functionalTest/resources/scenarios/RIA-3386-without-hearing-requirements-submitted-flag-no.json, src/functionalTest/resources/scenarios/RIA-3386-without-hearing-requirements-submitted-ftpa-reheard.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerWithoutHearingRequirementsPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerWithoutHearingRequirementsPersonalisationTest.java
[RIA-3386](https://tools.hmcts.net/jira/browse/RIA-3386)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3386 reheard hearing requirements not submitted

src/functionalTest/resources/scenarios/RIA-2047-RIA-2694-RIA-3593-direction-request-hearing-requirements.json, src/functionalTest/resources/scenarios/RIA-2048-RIA-2694-RIA-3593-direction-request-hearing-requirements-legal-rep.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRequestHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerResponseRequestHearingRequestPersonalisationTest.java
[RIA-3593](https://tools.hmcts.net/jira/browse/RIA-3593)
```
[ ] Yes
[x] No
```
=> RIA-3593 Notify CO of hearing requirements standard Direction

build.gradle
https://tools.hmcts.net/jira/browse/RIA-3670
updated dependabot depdendcies (changes from  PRs 420, 423, 425, 426)
```
[ ] Yes
[X] No
```
=> RIA-3670: updated dependabot depdendcies (changes from  PRs 420, 423, 425, 426)

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-3689-send-appeal-submitted-with-remission-pa-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3689-send-appeal-submitted-with-remission-pending-payment-ea-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3689-send-appeal-submitted-with-remission-pending-payment-hu-appeal-type-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RemissionType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPayOfflinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPendingPaymentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayLaterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayOfflinePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPendingPaymentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RemissionTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPayOfflinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPendingPaymentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayLaterPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayOfflinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPendingPaymentPersonalisationTest.java
RIA-3689-notification for remission for LR and AO
https://tools.hmcts.net/jira/browse/RIA-3689
```
[ ] Yes
[x ] No
```
=> RIA-3689-notification for remission for LR and AO

src/functionalTest/resources/scenarios/RIA-3690-appeal-with-remission-approved-ea-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3690-appeal-with-remission-approved-hu-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3690-appeal-with-remission-approved-pa-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3690-remission-decision-partially-approved.json, src/functionalTest/resources/scenarios/RIA-3690-remission-decision-rejected.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RemissionDecision.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealRemissionApprovedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerRemissionDecisionPartiallyApprovedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionApprovedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionPartiallyApprovedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionRejectedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RemissionDecisionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RemissionTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealRemissionApprovedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPayOfflinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedPendingPaymentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerRemissionDecisionPartiallyApprovedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPayOfflinePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPendingPaymentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionApprovedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionPartiallyApprovedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionRejectedPersonalisationTest.java
[RIA-3690](https://tools.hmcts.net/jira/browse/RIA-3690)
Remission notification for partially-approved and rejected
```
[ ] Yes
[x] No
```
=> RIA-3690 Remission decision notifications for partially-approved and rejected

config/owasp/suppressions.xml
N/A
fix suppress vulnerability
```
[ ] Yes
[x] No
```
=> fix suppress vulnerability

src/functionalTest/resources/scenarios/RIA-3305-async-stitching-ho-notification-failure.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAsyncStitchingHomeOfficeNotificationFailedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAsyncStitchingHomeOfficeNotificationFailedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-3305
RIA-3305 hearing bundle ready
```
[ ] Yes
[X] No
```
=> RIA-3305_hearing_bundle_ready

src/functionalTest/resources/scenarios/RIA-3313-appellant-ftpa-submitted-ho-notification-failure.json, src/functionalTest/resources/scenarios/RIA-3313-respondent-ftpa-submitted-ho-notification-failure.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerFtpaSubmittedHomeOfficeNotificationFailedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerFtpaSubmittedHomeOfficeNotificationFailedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-3313
Case Officer notification on FTPA submitted home office notification failure
```
[ ] Yes
[X] No
```
=> RIA-3313: Case Officer notification on FTPA submitted home office notification failure

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProviderTest.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestNewHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/DirectionFinderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-3776
Spring boot upgrade to 2.3.3
```
[ ] Yes
[X] No
```
=> RIA-3776: Spring boot upgrade to 2.3.3

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-3855-decision-outcome-admin-home-office-notification-failure.json, src/functionalTest/resources/scenarios/RIA-3855-decision-outcome-caseofficer-home-office-notification-failure.json, src/functionalTest/resources/scenarios/RIA-3855-decision-outcome-judge-home-office-notification-failure.json, src/functionalTest/resources/scenarios/RIA-3855-ftpa-decided-appellant-granted-after-appellant-granted.json, src/functionalTest/resources/scenarios/RIA-3855-ftpa-submitted-appellant-granted-after-appellant-granted.json, src/functionalTest/resources/scenarios/RIA-3855-ftpa-submitted-respondent-granted-after-appellant-granted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAppealOutcomeHomeOfficeNotificationFailedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerFtpaDecisionHomeOfficeNotificationFailedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAppealOutcomeHomeOfficeNotificationFailedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerFtpaDecisionHomeOfficeNotificationFailedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-3855
RIA-3855 Court_Outcome failed - gov notify
```
[ ] Yes
[X] No
```
=> RIA-3855_Court_Outcome

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-3837
RIA-3837 ooc legal rep
```
[ ] Yes
[X] No
```
=> RIA-3837_ooc_legal_rep

charts/ia-case-notifications-api/Chart.yaml
[RIA-3710](https://tools.hmcts.net/jira/browse/RIA-3710)
```
[ ] Yes
[x] No
```
=> RIA-3710 Migrate to Helm charts v2

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentre.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentreTest.java
[RIA-3810](https://tools.hmcts.net/jira/browse/RIA-3810)
Belfast hearing centre added
```
[ ] Yes
[x] No
```
=> RIA-3810 Belfast hearing centre added

.github/workflows/swagger.yml, build.gradle
[RIA-4121](https://tools.hmcts.net/jira/browse/RIA-4121)
```
[ ] Yes
[x] No
=> RIA-4121 Upgrade Tomcat version from 9.0.40 to 9.0.43

src/functionalTest/resources/scenarios/RIA-3720-case-listed-notification-birmingham-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-3720-case-listed-notification-remote-hearing.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProviderTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentre.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealService.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentreTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-3720
see ticket
```
[ ] Yes
[ X] No
```
=> RIA-3720 AO lists the case (remote hearing)

src/functionalTest/resources/scenarios/RIA-1380-edit-case-listing-notification-bradford-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1380-edit-case-listing-notification-newport-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1616-admin-office-edit-case-listing-notification-bradford-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-birmingham-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-glasgow-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-hatton-cross-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-north-shields-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-3720-case-listed-notification-remote-hearing.json, src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-notification-remote-hearing-no-change.json, src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-notification-remote-hearing.json, src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-notification-transfer-hearing-centre-to-remote.json, src/functionalTest/resources/scenarios/RIA-3722-edit-case-listing-notification-transfer-remote-to-hearing-centre.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProviderTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingNoChangePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditListingNoChangePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentreTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerEditListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingNoChangePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditListingNoChangePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
[RIA-3722](https://tools.hmcts.net/jira/browse/RIA-3722)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-3722 edit listing for remote hearing

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/consumer/IdamApiConsumerApplication.java, src/contractTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/consumer/IdamApiConsumerTest.java
TA-543
Added consumer contract tests
```
[ ] Yes
[X] No
```
=> TA-543 Consumer Contracts implemented

src/functionalTest/resources/scenarios/RIA-3731-remove-representation-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/postsubmit/PostSubmitNotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveRepresentationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRemoveRepresentationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemoveRepresentationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PostSubmitCallbackDispatcher.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/controllers/PostSubmitCallbackController.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/postsubmit/PostSubmitNotificationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveRepresentationPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRemoveRepresentationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemoveRepresentationPersonalisationTest.java
[RIA-3731](https://tools.hmcts.net/jira/browse/RIA-3731)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3731 remove representation

src/functionalTest/resources/scenarios/RIA-3951-remove-representation-notifications-admin-officer.json, src/functionalTest/resources/scenarios/RIA-3951-remove-representation-notifications-tcw.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/postsubmit/PostSubmitNotificationHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisationTest.java
[RIA-3951](https://tools.hmcts.net/jira/browse/RIA-3951)
See Jira
```
[ ] Yes
[x] No
```
=> Ria 3951 remove legal rep

.github/workflows/swagger.yml, src/functionalTest/resources/scenarios/RIA-3218-apply-for-a-late-remission.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerRequestFeeRemissionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestFeeRemissionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerRequestFeeRemissionPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestFeeRemissionPersonalisationTest.java
[RIA-3218](https://tools.hmcts.net/jira/browse/RIA-3218)
Legal rep apply for a late remission
```
[ ] Yes
[x] No
```
=> RIA-3218 Legal rep apply for a late remission

audit.json
N/A
suppressing new endpoint in the service
```
[ ] Yes
[x] No
```
=> suppressing new endpoint in the service

src/functionalTest/resources/scenarios/RIA-3800-manage-fee-update-for-refund-instructed.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeManageFeeUpdatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeManageFeeUpdatePersonalisationTest.java
[RIA-3800](https://tools.hmcts.net/jira/browse/RIA-3800)
Notification of manage fee update for refund instructed
```
[ ] Yes
[x] No
```
=> RIA-3800 Notification of manage fee update for refund instructed

src/functionalTest/resources/scenarios/RIA-3731-remove-representation-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeNocRequestDecisionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemoveRepresentationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeNocRequestDecisionPersonalisationTest.java
N/A
unsuppress NoC notifications
```
[ ] Yes
[x] No
```
=> unsuppress NoC notifications

build.gradle, charts/ia-case-notifications-api/Chart.yaml
[RIA-4278](https://tools.hmcts.net/jira/browse/RIA-4278)
fix cve and upgrade Charts
```
[ ] Yes
[x] No
```
=> RIA-4278 fix CVE and upgrade Charts

Jenkinsfile_CNP
Enable CanIDeploy in Jenkins pipeline
```
[ ] Yes
[ x] No
```
=> TA-543: Enable CanIDeploy in Jenkins pipeline

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHearingBundleFailedPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHearingBundleFailedPersonalisationTest.java
[RIA-4106](https://tools.hmcts.net/jira/browse/RIA-4106)
```
[ ] Yes
[x] No
```
=> RIA-4106 Different progress image in overview tab

src/functionalTest/resources/scenarios/RIA-2323-case-listed-notification-coventry-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-2323-case-listed-notification-nottingham-hearing-centre.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
[RIA-4047](https://tools.hmcts.net/jira/browse/RIA-3990)
Set the hearing centre has Birmingham for Coventry and Nottingham postcodes
```
[ ] Yes
[x] No
```
=> RIA-4047 Set hearing centre as Birmingham for Coventry and Nottingham postcodes

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/RIA-1431-RIA-2974-ftpa-applicant-appeal-decision-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-ftpa-applicant-appeal-decision-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-ftpa-applicant-appeal-decision-partially-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-ftpa-applicant-appeal-decision-partially-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-2975-ftpa-applicant-appeal-decision-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-ftpa-applicant-appeal-decision-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-2975-ftpa-applicant-appeal-decision-partially-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-ftpa-applicant-appeal-decision-partially-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-2999-RIA-3003-ftpa-respondent-granted-after-appellant-refused.json, src/functionalTest/resources/scenarios/RIA-2999-ftpa-appellant-granted-after-respondent-granted.json, src/functionalTest/resources/scenarios/RIA-2999-ftpa-appellant-partially-granted-after-respondent-not-addmitted.json, src/functionalTest/resources/scenarios/RIA-2999-ftpa-respondent-granted-after-appellant-granted.json, src/functionalTest/resources/scenarios/RIA-3855-ftpa-decided-appellant-granted-after-appellant-granted.json, src/functionalTest/resources/scenarios/RIA-3855-ftpa-submitted-appellant-granted-after-appellant-granted.json, src/functionalTest/resources/scenarios/RIA-3855-ftpa-submitted-respondent-granted-after-appellant-granted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerFtpaDecisionAppellantPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerFtpaDecisionRespondentPersonalisation.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
[RIA-4320](https://tools.hmcts.net/jira/browse/RIA-4320)
```
[ ] Yes
[x] No
```
=> RIA-4320 Approved FTPA decision email is not received

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-after-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-before-listing-AO.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-before-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-before-listing-judge.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantEndAppealPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantEndAppealPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantEndAppealPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantEndAppealPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4321
AIP appellant (SMS and email) and Home Office email notifications on endAppeal
```
[ ] Yes
[X] No
```
=> RIA-4321: AIP appellant (SMS and email) and Home Office email notifications on endAppeal

src/functionalTest/resources/scenarios/RIA-4355-record-out-of-time-decision-appeal-cannot-proceed-aip-CO.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4355
Record out of time decision for appellant application - cannot proceed notifications
```
[ ] Yes
[X] No
```
=> Ria 4355 oot appellant refused

src/functionalTest/resources/scenarios/RIA-4356-record-out-of-time-decision-appeal-can-proceed-aip-CO.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRecordOutOfTimeDecisionCanProceedPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRecordOutOfTimeDecisionCanProceedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRecordOutOfTimeDecisionCanProceedPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRecordOutOfTimeDecisionCanProceedPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4356
Record out of time decision can proceed appellant notifications 
```
[ ] Yes
[X] No
```
=> Ria 4356 oot appellant granted

src/functionalTest/resources/scenarios/RIA-4473-decision-without-hearing-notification-to-home-office.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentre.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentreTest.java
[RIA-4473](https://tools.hmcts.net/jira/browse/RIA-4473)
```
[ ] Yes
[x] No
```
=> RIA-4473 Decision without hearing route

Jenkinsfile_nightly
N/A
functional test fix in nightly build
```
[ ] Yes
[x] No
```
=> functional test fix in nightly build

Jenkinsfile_nightly
N/A
functional test fix in nightly build url
```
[ ] Yes
[x] No
```
=> functional test fix in nigthly build url

src/functionalTest/resources/scenarios/RIA-3488-end-appeal-home-office-notification-before-listing.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-after-listing-CO.json
N/A
change ids in functional tests
```
[ ] Yes
[x] No
```
=> change ids in functional tests

Jenkinsfile_nightly
N/A
test url change
```
[ ] Yes
[x] No
```
=> test url change

src/functionalTest/resources/scenarios/RIA-2828-aip-send-notifications-request-more-time-appellant-case-officer-reasons-for-appeal.json, src/functionalTest/resources/scenarios/RIA-2976-aip-send-notifications-request-more-time-appellant-case-officer-clarifying-questions.json, src/functionalTest/resources/scenarios/RIA-3153-aip-send-notifications-request-more-time-appellant-case-officer-cma-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-4336
Integrating AiP flow and make an application event for citizen
```
[ ] Yes
[ x ] No
```
=> RIA-4336: Integrating AiP flow and make an application event for citizen

src/functionalTest/resources/scenarios/RIA-2405-RIA-2936-RIA-4359-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-3488-RIA-4359-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-3631-RIA-4359-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealOutOfTimePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealOutOfTimePersonalisationSms.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealOutOfTimePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmitAppealOutOfTimePersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4359
Amend out of time appeal submission appellant notifications
```
[ ] Yes
[X] No
```
=> RIA-4359: Amend out of time appeal submission appellant notifications

src/functionalTest/resources/scenarios/RIA-2828-aip-send-notifications-request-more-time-appellant-case-officer-reasons-for-appeal.json, src/functionalTest/resources/scenarios/RIA-2976-aip-send-notifications-request-more-time-appellant-case-officer-clarifying-questions.json, src/functionalTest/resources/scenarios/RIA-3153-aip-send-notifications-request-more-time-appellant-case-officer-cma-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMakeAnApplicationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMakeAnApplicationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMakeAnApplicationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMakeAnApplicationPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4387
Appellant request for more time before starting appeal reasons event notifications (Email and SMS)
```
[ ] Yes
[X] No
```
=> Ria 4387 Appellant request for more time before starting appeal reasons event notifications (Email and SMS)

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java
https://tools.hmcts.net/jira/browse/RIA-4380
Added missing state causing issue for aip flow
```
[ ] Yes
[X] No
```
=> RIA-4380: Added missing state causing issue for aip flow

build.gradle
N/A
Remove bintray + add default maven repos
```
[ ] Yes
[x] No
```
=> Remove bintray

src/functionalTest/resources/scenarios/RIA-4546-appeal-exited-online-aip-notification.json, src/functionalTest/resources/scenarios/RIA-4546-link-appeal-aip-notification.json, src/functionalTest/resources/scenarios/RIA-4546-send-change-hearing-centre-aip-notification.json, src/functionalTest/resources/scenarios/RIA-4546-unlink-appeal-aip-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java
https://tools.hmcts.net/jira/browse/RIA-4546
Added appellant notifications flow (notification to be followed in different stories) for linkAppeal, unlinkAppeal and changeHearingCentre
```
[ ] Yes
[X] No
```
=> RIA-4546: Added appellant notifications flow (notification to be followed in different stories) for linkAppeal, unlinkAppeal and changeHearingCentre

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-4604
Fixed decideAnApplication error for aip appeals
```
[ ] Yes
[X] No
```
=> RIA-4604: Fixed decideAnApplication error for aip appeals

Jenkinsfile_nightly, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml
[RIA-4262](https://tools.hmcts.net/jira/browse/RIA-4262)
AIP PerfTest env
```
[ ] Yes
[x] No
```
=> RIA-4262 Move to the gov.uk subdomain

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties
[RIA-4474](https://tools.hmcts.net/jira/browse/RIA-4474)
Enabled fortify scan in the nightly pipeline
```
[ ] Yes
[x] No
```
=> RIA-4474 Enabled Fortify scan for Jenkins nightly

Jenkinsfile_nightly, config/fortify-client.properties
[RIA-4474](https://tools.hmcts.net/jira/browse/RIA-4557)
Fortify scan
```
[ ] Yes
[x] No
```
=> RIA-4474 Enabled Fortify scan (#567)

build.gradle
[RIA-4474](https://tools.hmcts.net/jira/browse/RIA-4474)
Fortify-client lib issue
```
[ ] Yes
[x] No
```
=> RIA-4474 JitPack repo

src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-after-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-after-listing-judge.json, src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-before-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-before-listing-judge.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationRefusedPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationRefusedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationRefusedPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationRefusedPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-4389
Added AIP and HO notifications for when decideAnApplication refuses the made application
```
[ ] Yes
[X] No
```
=> Ria 4389 - Added AIP and HO notifications for when decideAnApplication refuses the made application

src/functionalTest/resources/scenarios/RIA-4626-send-respondent-review-direction-HO-govnotify-disabled-aip.json, src/functionalTest/resources/scenarios/RIA-4626-send-respondent-review-direction-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRespondentReviewPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRespondentReviewPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRespondentReviewPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRespondentReviewPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4626
Added AIP flow notifications for requestRespondent events -added/updated functional tests
```
[ ] Yes
[X] No
```
=> RIA-4626: Added AIP flow notifications for requestRespondent events -added/updated functional tests

.gitignore, src/functionalTest/resources/scenarios/RIA-1431-RIA-2974-RIA-4352-ftpa-applicant-appeal-decision-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-RIA-4352-ftpa-applicant-appeal-decision-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-RIA-4352-ftpa-applicant-appeal-decision-partially-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-1432-RIA-2974-RIA-4352-ftpa-applicant-appeal-decision-partially-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-4352-ftpa-applicant-appeal-decision-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-4352-ftpa-applicant-appeal-decision-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-4352-ftpa-applicant-appeal-decision-partially-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-4352-ftpa-applicant-appeal-decision-partially-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-3631-RIA-4352-ftpa-applicant-appeal-decision-partially-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-4352-upper-tribunal-bundle-failed-notification-to-admin-officer.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerUpperTribunalBundleFailedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerUpperTribunalBundleFailedPersonalisationTest.java
[RIA-4352](https://tools.hmcts.net/jira/browse/RIA-4352)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-4352 upper tribunal notifications

src/functionalTest/resources/scenarios/RIA-3103-request-response-amend.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestRespondentAmendDirectionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestRespondentAmendDirectionPersonalisationTest.java
[RIA-4371](https://tools.hmcts.net/jira/browse/RIA-4371)
```
[ ] Yes
[x] No
```
=> RIA-4371 Notification for a LR when HO directed to amend response

src/functionalTest/resources/scenarios/RIA-4690-request-response-amend-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestResponseAmendPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestResponseAmendPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestResponseAmendPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestResponseAmendPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4690
Appellant notifications on request response amend to HomeOffice
```
[ ] Yes
[X] No
```
=> RIA-4690: Appellant notifications on request response amend to HomeOffice

src/functionalTest/resources/scenarios/RIA-4646-request-response-review-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealReviewOutcome.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestResponseReviewPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestResponseReviewPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealReviewOutcomeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestResponseReviewPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestResponseReviewPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4646
request for response review notification to appellant (AiP)upon withdrawn decision from Homeoffice response
```
[ ] Yes
[X] No
```
=> RIA-4646: request for response review notification to appellant (AiP)upon withdrawn decision from Homeoffice response

src/functionalTest/resources/scenarios/RIA-4646-request-response-review-withdrawn-aip.json, src/functionalTest/resources/scenarios/RIA-4649-request-response-review-maintained-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealReviewOutcome.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestResponseReviewPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestResponseReviewPersonalisationSms.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestResponseReviewPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRequestResponseReviewPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4649
request for response review notification to appellant (AiP) upon maintained decision from Homeoffice response
```
[ ] Yes
[X] No
```
=> Ria 4649 - request for response review notification to appellant (AiP) upon maintained decision from Homeoffice response

src/functionalTest/resources/scenarios/RIA-4961-edit-payment-method-payment-notifications-remission-rejected-ea-appeal.json, src/functionalTest/resources/scenarios/RIA-4961-edit-payment-method-payment-notifications-remissions-rejected-hu-appeal.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-4961
Remission rejected - payment method updated to card - Removal of notification to Leg Rep and HO
```
[ ] Yes
[X] No
```
=> RIA-4961: Remission rejected - payment method updated to card - Removal of notification to Leg Rep and HO

charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml
Remissions release
Adding payments exception admin email address for prod
```
[ ] Yes
[x] No
```
=> Adding for payments exception email address for prod

src/main/resources/application.yaml
N/A
Updated default email payment exceptions email address
```
[ ] Yes
[x] No
```
=> updated default email for payment exceptions admin officer

src/functionalTest/resources/scenarios/RIA-4861-case-listed-notification-birmingham-hearing-centre-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantListCasePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantListCasePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantListCasePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantListCasePersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-4861
case listed notifications to CO, Homeoffice and appellant (email and sms) for AIP journey
```
[ ] Yes
[X] No
```
=> RIA-4861: case listed notifications to CO, Homeoffice and appellant (email and sms) for AIP journey

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/main/resources/bootstrap.yaml
N/A
Missing config for Launch Darkly in notifications.
```
[ ] Yes
[x] No
```
=> Missing configuration for LD flag

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-4691
editAppealAfterSubmit role-event access added for citizen
```
[ ] Yes
[X] No
```
=> RIA-4691: editAppealAfterSubmit role-event access added for citizen

src/functionalTest/resources/scenarios/RIA-3720-case-listed-notification-remote-hearing.json, src/functionalTest/resources/scenarios/RIA-4975-case-listed-notification-remote-hearing-centre-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantListCasePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantListCasePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinder.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantListCasePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantListCasePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
[RIA-4795](https://tools.hmcts.net/jira/browse/RIA-4975)
List case - Remote hearing - Notifications content update to how location as 'Remote hearing'
=> feat: List case - Remote hearing - Notifications content update to how location as 'Remote hearing' [RIA-4795]

src/functionalTest/resources/scenarios/RIA-4848-submitted-hearing-requirements-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmittedHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmittedHearingRequirementsPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmittedHearingRequirementsPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmittedHearingRequirementsPersonalisationSmsTest.java
=> RIA-4848 Submit Hearing requirements: Appellant notification

src/functionalTest/resources/scenarios/RIA-1463-send-appeal-allowed-decision-notification.json, src/functionalTest/resources/scenarios/RIA-1463-send-appeal-dismissed-decision-notification.json, src/functionalTest/resources/scenarios/RIA-1939-send-appeal-allowed-decision-notification-admin.json, src/functionalTest/resources/scenarios/RIA-1939-send-appeal-dismissed-decision-notification-judge.json, src/functionalTest/resources/scenarios/RIA-3631-send-appeal-allowed-decision-notification-admin.json, src/functionalTest/resources/scenarios/RIA-3631-send-appeal-dismissed-decision-notification-judge.json, src/functionalTest/resources/scenarios/RIA-3855-decision-outcome-admin-home-office-notification-failure.json, src/functionalTest/resources/scenarios/RIA-3855-decision-outcome-caseofficer-home-office-notification-failure.json, src/functionalTest/resources/scenarios/RIA-3855-decision-outcome-judge-home-office-notification-failure.json, src/functionalTest/resources/scenarios/RIA-4932-aip-appeal-outcome-allowed.json, src/functionalTest/resources/scenarios/RIA-4932-aip-appeal-outcome-dismissed.json, src/functionalTest/resources/scenarios/RIA-4932-aip-ooc-appeal-outcome-allowed.json, src/functionalTest/resources/scenarios/RIA-4932-ooc-aip-appeal-outcome-dismissed.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantAppealOutcomePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantAppealOutcomePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantAppealOutcomePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantAppealOutcomePersonalisationSmsTest.java
[RIA-4932](https://tools.hmcts.net/jira/browse/RIA-4932)
```
[ ] Yes
[x] No
```
=> RIA-4932 Decision - Appellant notification

src/functionalTest/resources/scenarios/RIA-4929-hearing-bundle-is-ready-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantHearingBundleReadyPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantHearingBundleReadyPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantHearingBundleReadyPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantHearingBundleReadyPersonalisationSmsTest.java
=> RIA-4929 Bundle ready - Appellant notification

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/SendsDirectionTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/Direction.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerUploadAddendumEvidencePersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerUploadAddendumEvidencePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-4540
Added uniqueId and directionType fields to Direction
```
[ ] Yes
[X] No
```
=> RIA-4540: Added uniqueId and directionType fields to Direction

charts/ia-case-notifications-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```
=> RIA-5503: Upgrade base helm charts to latest

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealPersonalisationEmail.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmitAppealPersonalisationEmailTest.java
[RIA-5157](https://tools.hmcts.net/jira/browse/RIA-5157)
See Jira
```
[ ] Yes
[x] No
```
=> RIA-5157 aip ooc notification with no home office reference

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/bail/RIA-5584-send-bail-application-submitted-notification-to-newport-hearing-centre.json, src/functionalTest/resources/templates/minimal-bail-application-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/UserRole.java, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/UserRoleTest.java
=> RIA-5584: Add functional tests for HC

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java
=> RIA-5610: Remove unused ccd field definitions

src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications-not-legally-represented.json, src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications.json, src/functionalTest/resources/templates/minimal-bail-application-ended-not-legally-represented.json, src/functionalTest/resources/templates/minimal-bail-application-ended.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/BaseNotificationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailApplicationEndedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailApplicationEndedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailApplicationEndedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/ApplicantBailApplicationEndedPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailApplicationEndedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/LegalRepresentativeBailApplicationEndedPersonalisationTest.java
[RIA-5214](https://tools.hmcts.net/jira/browse/RIA-5214)
Send notifications when the application is ended to:
- applicant (sms)
- home office (email)
- legal representative if present (email)
```
[ ] Yes
[x] No
```
=> Ria 5214 send notifications for application ended

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/SendsDirectionTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/NotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/CaseType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailEmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailSmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/SmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelper.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-5750
Split GovNotifyNotificationSender into BailGovNotifyNotificationSender
Tested both Appeal and Bail notifications and bail 
```
[ ] Yes
[ x ] No
```
=> RIA-5750 Updated rebased code

src/functionalTest/resources/scenarios/bail/RIA-5553-send-bail-documents-uploaded-notification-with-LR.json, src/functionalTest/resources/scenarios/bail/RIA-5553-send-bail-documents-uploaded-notification-without-LR.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailDocumentUploadedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailDocumentUploadedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailDocumentUploadedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/LegalRepresentativeBailDocumentUploadedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-5553
Early RP for code review only. 
Need https://tools.hmcts.net/jira/browse/RIA-5545 MERGED before this can PR can be merged.
```
[ ] Yes
[ x ] No
```
=> Ria 5553 document uploaded notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java
https://tools.hmcts.net/jira/browse/RIA-5801
Added new make new application event
```
[ ] Yes
[ x ] No
```
=> RIA-5801 added make new application event

src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications-not-legally-represented.json, src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications.json, src/functionalTest/resources/scenarios/bail/RIA-5476-send-bail-application-submitted-notification-to-applicant-sms.json, src/functionalTest/resources/scenarios/bail/RIA-5561-send-bail-signed-decision-notice-notifications-not-legally-represented.json, src/functionalTest/resources/scenarios/bail/RIA-5561-send-signed-decision-notice-notifications.json, src/functionalTest/resources/templates/minimal-bail-application-ended-not-legally-represented.json, src/functionalTest/resources/templates/minimal-bail-application-ended.json, src/functionalTest/resources/templates/minimal-bail-record-the-decision-not-legally-represented.json, src/functionalTest/resources/templates/minimal-bail-record-the-decision.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/ApplicantBailSmsNotificationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/ApplicantBailApplicationEndedPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/ApplicantBailApplicationSubmittedPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/ApplicantBailSignedDecisionNoticeUploadedPersonalisationSmsTest.java
[RIA-5905](https://tools.hmcts.net/jira/browse/RIA-5905)
- Update field names to reflect changes in ia-bail-case-api
**Fields affected:**
applicantMobileNumber
financialCondAmount
supporterTelephoneNumber
supporterMobileNumber
supporterEmailAddress
financialAmountSupporterUndertakes
supporter2TelephoneNumber
supporter2MobileNumber
supporter2EmailAddress
financialAmountSupporter2Undertakes
supporter3TelephoneNumber
supporter3MobileNumber
supporter3EmailAddress
financialAmountSupporter3Undertakes
supporter4TelephoneNumber
supporter4MobileNumber
supporter4EmailAddress
financialAmountSupporter4Undertakes
```
[ ] Yes
[x] No
```
=> RIA-5905 Update field names

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/CcdScenarioRunnerTest.java, src/functionalTest/resources/scenarios/RIA-5808-aip-admin-officer-upload-addendum-evidence-notification.json, src/functionalTest/resources/scenarios/RIA-5808-aip-case-officer-upload-addendum-evidence-notification.json, src/functionalTest/resources/scenarios/RIA-5808-aip-home-office-upload-addendum-evidence-notification.json, src/functionalTest/resources/scenarios/RIA-5811-aip-upload-addendum-evidence-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantHomeOfficeUploadAddendumEvidencePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantTcwUploadAddendumEvidencePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantUploadAddendumEvidencePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantHomeOfficeUploadAddendumEvidencePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantTcwUploadAddendumEvidencePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantUploadAddendumEvidencePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantHomeOfficeUploadAddendumEvidencePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantTcwUploadAddendumEvidencePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantUploadAddendumEvidencePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantHomeOfficeUploadAddendumEvidencePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantTcwUploadAddendumEvidencePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantUploadAddendumEvidencePersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-5808
```
[ ] Yes
[x] No
```
=> RIA-5808: HO/TCW add an addendum - Appellant Notification

charts/ia-case-notifications-api/Chart.yaml
=> upgrade Charts Java plat dependency

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantEndAppealPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantEndAppealPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationSms.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantEndAppealPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantEndAppealPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRecordOutOfTimeDecisionCannotProceedPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-5835
```
[ ] Yes
[x] No
```
=> RIA-5835: code refactoring

src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-after-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-before-listing-AO.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-before-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-before-listing-judge.json, src/functionalTest/resources/scenarios/RIA-4827-appeal-ended-no-payment-status-aip.json, src/functionalTest/resources/scenarios/RIA-4827-appeal-ended-payment-failed-aip.json, src/functionalTest/resources/scenarios/RIA-4827-appeal-ended-payment-pending-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantEndAppealPersonalisationSms.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantEndAppealPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-5835
```
[ ] Yes
[x] No
```
=> RIA-5835: Update 'AIP Ended appeal' notification template

src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-after-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-after-listing-judge.json, src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-before-listing-CO.json, src/functionalTest/resources/scenarios/RIA-4389-decide-an-application-notification-aip-refused-before-listing-judge.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMakeAnApplicationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMakeAnApplicationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/MakeAnApplicationService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMakeAnApplicationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMakeAnApplicationPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerMakeAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeDecideAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMakeAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/MakeAnApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-5833
```
[ ] Yes
[x] No
```
=> RIA-5833: Update Refusal application decision notification template

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationPersonalisationSms.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-6089
```
[ ] Yes
[x] No
```
=> RIA-6089: Fix Other pary Application Decided Notification in AIP journey

src/functionalTest/resources/scenarios/RIA-6089-aip-decide-an-application-notification-home-office-apc-granted-after-listing.json, src/functionalTest/resources/scenarios/RIA-6089-aip-decide-an-application-notification-home-office-apc-granted-before-listing.json, src/functionalTest/resources/scenarios/RIA-6089-aip-decide-an-application-notification-home-office-apc-refused-after-listing.json, src/functionalTest/resources/scenarios/RIA-6089-aip-decide-an-application-notification-home-office-apc-refused-before-listing.json
https://tools.hmcts.net/jira/browse/RIA-6089
```
[ ] Yes
[x] No
```
=> RIA-6089: Write Functional tests

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-5725
QA fix for notifications not being sent, corrected wrong bean name.
```
[ ] Yes
[X] No
```
=> RIA-5725 Fixed bean names for LR and HO notifications

build.gradle, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealType.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealTypeTest.java
- [RIA-5587](https://tools.hmcts.net/jira/browse/RIA-5587)
- [RIA-5895](https://tools.hmcts.net/jira/browse/RIA-5895)
- [RIA-5586](https://tools.hmcts.net/jira/browse/RIA-5586)
- [RIA-6163](https://tools.hmcts.net/jira/browse/RIA-6163)
- Added EU ("EU Settlement Scheme" to AppealType enum)
```
[ ] Yes
[x] No
```
=> RIA-5587 Add EU appealType

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-3951-remove-representation-notifications-admin-officer.json, src/functionalTest/resources/scenarios/RIA-3951-remove-representation-notifications-tcw.json, src/functionalTest/resources/scenarios/RIA-6043-remove-representation-notifications-letter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/NotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/PinInPostDetails.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantRemoveRepresentationPersonalisationLetter.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveRepresentationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/LetterNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/RetryableNotificationClient.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantRemoveRepresentationPersonalisationLetterTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveRepresentationPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/RetryableNotificationClientTest.java
https://tools.hmcts.net/jira/browse/RIA-6043
```
[ ] Yes
[x] No
```
=> RIA-6043 Appellant receives Notification when LR comes off record

src/functionalTest/resources/scenarios/RIA-4084-send-apply-notice-of-change-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-4084-send-apply-notice-of-change-notification-to-appellant-sms.json, src/functionalTest/resources/scenarios/RIA-5966-send-apply-notice-of-change-notification-after-listingForAIP.json, src/functionalTest/resources/scenarios/RIA-5966-send-apply-notice-of-change-notification-before-listingForAIP.json, src/functionalTest/resources/scenarios/RIA-5966-send-apply-notice-of-change-notification-to-appellant-smsForAIP.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeNocRequestAipDecisionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeNocRequestAipDecisionPersonalisationTest.java
=> RIA-5966: Introduced notification for Applelant to LR access change.

src/functionalTest/resources/scenarios/RIA-3731-remove-representation-notifications-email.json, src/functionalTest/resources/scenarios/RIA-3731-remove-representation-notifications-sms.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRemoveRepresentationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRemoveRepresentationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6044
```
[ ] Yes
[x] No
```
=> RIA-6044 LR/HO/TCW receives Notification of Change

src/main/resources/application.yaml
=> RIA-5965: Allow caseworker-caa role to execute NoCRequestBail Event

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/BaseNotificationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantRemoveRepresentationPersonalisationLetter.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveRepresentationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRemoveRepresentationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveRepresentationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantRemoveRepresentationPersonalisationLetterTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveRepresentationPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRemoveRepresentationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6043
```
[ ] Yes
[x] No
```
=> RIA-6043: Use the correct date format in notifications

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-6273
- Stopped notifications for LR, HO and Appellant SMS or Email when PA pay now was paid, and send when the case is submitted to behave like PA pay later
```
[ ] Yes
[X] No
```
=> RIA-6273 pa pay now notification sent when submitted

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-2118-send-appeal-submitted-to-home-office.json, src/functionalTest/resources/scenarios/RIA-6273-new-way-of-paying-lr-ho-appellant-appeal-submitted.json
=> RIA-6284 Fix functional test and new scenario PA pay now

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-2405-RIA-2936-RIA-4359-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-3472-send-appeal-submitted-dc-appeal-type-notification-legal-rep.json, src/functionalTest/resources/scenarios/RIA-3472-send-appeal-submitted-rp-appeal-type-notification-legal-rep.json, src/functionalTest/resources/scenarios/RIA-3488-RIA-4359-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-3488-send-appeal-submitted-to-home-office.json, src/functionalTest/resources/scenarios/RIA-3631-RIA-4359-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-365-RIA-2936-send-appeal-submitted-notification-to-taylor-house.json, src/functionalTest/resources/scenarios/RIA-3689-send-appeal-submitted-with-remission-pa-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3689-send-appeal-submitted-with-remission-pending-payment-ea-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3689-send-appeal-submitted-with-remission-pending-payment-hu-appeal-type-notification.json, src/functionalTest/resources/scenarios/RIA-3995-send-appeal-submitted-notifications-to-appellant-email.json, src/functionalTest/resources/scenarios/RIA-3995-send-appeal-submitted-notifications-to-appellant-sms.json
* Updated submitAppeal events with payment attributes required to work
* Removed unsupported Case Officer notifications from all these scenarios
=> Ria 6284 functional tests

src/functionalTest/resources/scenarios/RIA-1647-RIA-1276-RIA-2936-end-appeal-home-office-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-2239-RIA-2936-end-appeal-home-office-notification-judge-after-listing.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-after-listing-CO.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerManageFeeUpdatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativePendingPaymentPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerManageFeeUpdatePersonalisationTest.java
[RIA-6172](https://tools.hmcts.net/jira/browse/RIA-6172)
- Add EU to all options where EA and HU are an option (to integrate EU appeal types with new ways2Pay processes)
```
[ ] Yes
[x] No
```
=> RIA-6172 Add EU to all options with HU/EA

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentre.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-6455
Added Yarl's Wood location
```
[ ] Yes
[ x] No
```
=> Ria 6455 yarls wood location

config/owasp/suppressions.xml
merge conflict
merge conflict
```
[ ] Yes
[ ] No
```
=> resolve conflict

config/owasp/suppressions.xml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6491
```
[ ] Yes
[x] No
```
=> RIA-6491: Give admin officer access to edit appeal post submission

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/caselinking/CaseLink.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/caselinking/ReasonForLink.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeCaseLinkPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeCaseUnlinkPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeCaseLinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeCaseUnlinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeCaseLinkPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeCaseUnlinkPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeCaseLinkAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeCaseUnlinkAppealPersonalisationTest.java
RIA-6074
```
[ ] Yes
[ ] No
```
=> Ria 6074 link cases notification

src/main/resources/application.yaml
SNI-2650
Updates to add Mark appeal as paid for case officer
Updates to add Mark appeal as paid for case officer
```
[ ] Yes
[ ] No
```
=> Updates to add Mark appeal as paid for case officer

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-6434-send-appeal-submitted-aaa-appeal-type-notification-legal-rep.json, src/functionalTest/resources/scenarios/RIA-6434-send-appeal-submitted-ada-appeal-type-notification-legal-rep.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAppealSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-6434
Added new template for ADA and AAA email for LR.
Adjusted NotificationHandlerConfiguration, so that previous config won't pick up ADA appeal type.
```
[ ] Yes
[ x ] No
```
=> Ria 6434 submit application ada or aaa lr

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHomeOfficeBundlePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHomeOfficeBundlePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-6555
* Send a modified notification to legal rep on request respondent evidence event for ADA appeal
```
[ ] Yes
[x] No
```
=> RIA-6555 LR Notification when HO has been directed to submit the bundle

src/functionalTest/resources/scenarios/RIA-4861-case-listed-notification-birmingham-hearing-centre-aip.json, src/functionalTest/resources/scenarios/RIA-4975-case-listed-notification-remote-hearing-centre-aip.json, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6545
Added 5 new templates
```
[ ] Yes
[ x] No
```
=> New nots templates added

src/functionalTest/resources/scenarios/RIA-6671-aip-payment-appeal-ea-notifications.json, src/functionalTest/resources/scenarios/RIA-6671-aip-payment-appeal-euss-notifications.json, src/functionalTest/resources/scenarios/RIA-6671-aip-payment-appeal-hu-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6671
* Send notification to appellant on 'paymentAppeal' event when payment is successful in AIP journey for Eu/Ea/Hu appeals.
```
[ ] Yes
[x] No
```
=> RIA-6671 AIP Payment - Successful payment Notification

src/functionalTest/resources/scenarios/RIA-6556-case-listed-notification-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHomeOfficeBundlePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealService.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHomeOfficeBundlePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/AppealServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-6556
```
[ ] Yes
[x] No
```
=> Notify LR and HO when ADA case is listed

src/functionalTest/resources/scenarios/RIA-6555-standard-direction-hearing-requirements-ada.json, src/functionalTest/resources/scenarios/RIA-6559-edit-case-listing-notification-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEditListingPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6559
* Notifications to Legal rep and Home Office when Case Officer relists an ADA case
* Added missing functional test for [RIA-6555](https://tools.hmcts.net/jira/browse/RIA-6555)
```
[ ] Yes
[x] No
```
=> Notifications when AO re-lists case (LR,HO)

src/functionalTest/resources/scenarios/RIA-6557-ada-notification-submitted-hearing-requirements.json
https://tools.hmcts.net/jira/browse/RIA-6557
Adding functional test for ADA submit hearing requirements
```
[ ] Yes
[x] No
```
=> RIA-6557 - Adding functional test

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle, charts/ia-case-notifications-api/Chart.yaml
To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[X ] No
```
=> To upgrade java chart version

charts/ia-case-notifications-api/Chart.yaml
To revise chart version
To revise chart version
```
[ ] Yes
[X ] No
```
=> To revise chart version

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle, charts/ia-case-notifications-api/Chart.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6792
change the Remote hearing label to: Video hearing suitability for 
Notification: Case re-listed location name remote hearing (LR) (v3)
```
[ ] Yes
[x ] No
```
=> RIA-6792 Notice of Hearing LR remote video label change

build.gradle, src/functionalTest/resources/scenarios/RIA-6665-ftpa-appellant-not-admitted-in-country.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-appellant-partially-granted-out-of-country.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-appellant-refused-ada.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-respondent-not-admitted-in-country.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-respondent-partially-granted-out-of-country.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-respondent-refused-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeFtpaApplicationDecisionRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeFtpaApplicationDecisionAppellantPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/DueDateService.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/CountryHolidayDates.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/GovUkHolidayDatesClient.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/HolidayDate.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/HolidayLoader.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/HolidayService.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/UkHolidayDates.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeFtpaApplicationDecisionRespondentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeFtpaApplicationDecisionAppellantPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/DueDateServiceTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/CountryHolidayDatesTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/HolidayDateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/HolidayLoaderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/HolidayServiceTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/holidaydates/UkHolidayDatesTest.java
https://tools.hmcts.net/jira/browse/RIA-6665
* Implement DueDateService for calculating due dates based on working days and calendar days
* Dynamic dates for ftpa applicant (Legal Rep) decision notifications
* Dynamic dates for ftpa applicant (Respondent) decision notifications
```
[ ] Yes
[x] No
```
=> RIA-6665 Applicant notification changes - FTPA journey

src/functionalTest/resources/scenarios/RIA-1966-RIA-2936-RIA-6808-aip-send-appeal-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-3488-RIA-4359-RIA-6585-aip-send-appeal-out-of-time-submitted-notifications-to-appellant.json, src/functionalTest/resources/scenarios/RIA-3488-RIA-6585-aip-send-appeal-submitted-notifications-to-appellant.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-6808
```
[ ] Yes
[x] No
```
=> RIA-6808: AIP Payment - PA submission notifications(Pay now/Pay Later)

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java
https://tools.hmcts.net/jira/browse/RIA-6694
Allow admin to access the submitAppeal event. 
```
[ ] Yes
[x ] No
```
=> RIA-6694-Admin-Submit-Appeal

src/functionalTest/resources/scenarios/RIA-6802-notification-of-appellant-ftpa-submitted-for-ada.json, src/main/resources/application.yaml
- Added functional test for notifications to be sent out to Harmondsworth FTPA email address.
```
[ ] Yes
[x] No
```
=> RIA-6802: Added env variable for FTPA Email address for Harmondsworth

src/functionalTest/resources/scenarios/RIA-1497-RIA-2338-RIA-6701-send-edit-appeal-after-submit-after-listing-notification.json, src/functionalTest/resources/scenarios/RIA-1497-RIA-2338-RIA-6701-send-edit-appeal-after-submit-before-listing-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-6701
* Send notification only to respondent on edit appeal post submission event for internal case
```
[ ] Yes
[x] No
```
=> RIA-6701: Edit appeal (Post submission) - Detained Internal case

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6700
RIA-6700 - Allowing access to editAppeal for Admin users
```
[ ] Yes
[x] No
```
=> RIA-6700 - Allowing access to editAppeal for Admin users

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/DetEmailService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/DetEmailServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-6859
Added dummy email to yaml. Created service class to retrieve the yaml value. Added test class.
```
[ ] Yes
[X] No
```
=> RIA-6859 DET email address for ADA unrepresented notifications

src/functionalTest/resources/scenarios/RIA-6780-internal-ada-case-request-response-review-maintained.json, src/functionalTest/resources/scenarios/RIA-6780-internal-ada-case-request-response-review-withdrawn.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestResponseReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/TestUtils.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestResponseReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6780
```
[ ] Yes
[x] No
```
=> RIA-6780: Request response review notification for internal ADA cases

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestResponseReviewPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestResponseReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6780
```
[ ] Yes
[x] No
```
=> RIA-6780: Fix issue with parsing 'hearing date'

src/functionalTest/resources/scenarios/RIA-6784-det-notification-appellant-ftpa-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamFtpaSubmittedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6784
```
[ ] Yes
[x] No
```
=> RIA-6784: Appellant's FTPA submitted notification for Internal ADA cases

src/functionalTest/resources/scenarios/RIA-6785-det-notification-respondent-ftpa-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/OtherDetentionEngagementTeamFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/OtherDetentionEngagementTeamFtpaSubmittedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6785
* Create notification template
* Create email personalization
* Update Notification configuration handler and generator to send different sets of notifications for non-internal cases and internal ADA cases.
* Functional/Unit tests
```
[ ] Yes
[x] No
```
=> RIA-6785 Home Office's FTPA submitted notification for Internal ADA cases

Dockerfile, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeDecideAnApplicationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeDecideAnApplicationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6966
Updated the way listing ref is extracted
```
[ ] Yes
[X] No
```
=> RIA-6966 LR notification missing listing ref

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7001
Updating all personalisations related to FTPA decision, that attempts to obtain LR email address, to check if internal case.
Testing:
All scenarios are submitted successfully with no callback errors.
```
[ ] Yes
[X] No
```
=> RIA-7001 Resident judge FTPA decided callback error.

src/functionalTest/resources/scenarios/RIA-6112-ftpa-submitted-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaSubmittedPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaSubmittedPersonalisationEmailTest.java
[RIA-6112](https://tools.hmcts.net/jira/browse/RIA-6112)
- Added all necessary classes for notification being sent to AIP when citizen submits FTPA
```
[ ] Yes
[x] No
```
=> RIA-6112 FTPA submitted (AIP) notification

src/functionalTest/resources/scenarios/RIA-6112-ftpa-submitted-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaSubmittedPersonalisationEmail.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaSubmittedPersonalisationEmailTest.java
[RIA-6112](https://tools.hmcts.net/jira/browse/RIA-6112)
- Add `ariaListingReference` to notification
```
[ ] Yes
[x] No
```
=> RIA-6112 Tweak notification to standardize it

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveDetainedStatusPersonalisationEmail.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveDetainedStatusPersonalisationEmailTest.java
* Added appellant given/family names to personalisation
* Updated unit test
https://tools.hmcts.net/jira/browse/RIA-6940
Added appellant names to personlisation
```
[ ] Yes
[X] No
```
=> RIA-6940 Content fix to include appellant name in personlisation

src/functionalTest/resources/scenarios/RIA-6113-applicant-ftpa-decision-granted-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6113-applicant-ftpa-decision-granted-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6113-applicant-ftpa-decision-partially-granted-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6113-applicant-ftpa-decision-partially-granted-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6116-respondent-ftpa-decision-granted-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6116-respondent-ftpa-decision-granted-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6116-respondent-ftpa-decision-partially-granted-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6116-respondent-ftpa-decision-partially-granted-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6134-appellant-ftpa-decision-not-admitted-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6134-appellant-ftpa-decision-not-admitted-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6134-appellant-ftpa-decision-refused-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6134-appellant-ftpa-decision-refused-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6135-respondent-ftpa-decision-not-admitted-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6135-respondent-ftpa-decision-not-admitted-aip-journey-resident-judge.json, src/functionalTest/resources/scenarios/RIA-6135-respondent-ftpa-decision-refused-aip-journey-leadership-judge.json, src/functionalTest/resources/scenarios/RIA-6135-respondent-ftpa-decision-refused-aip-journey-resident-judge.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaApplicationDecisionPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantFtpaApplicationDecisionPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaApplicationDecisionPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantFtpaApplicationDecisionPersonalisationSmsTest.java
[RIA-6134](https://tools.hmcts.net/jira/browse/RIA-6134)
- Notifications for `leadershipJudgeFtpaDecision` and `residentJudgeFtpaDecision` when applicant type is **appellant** and outcome is `notAdmitted` and `refused`
```
[ ] Yes
[x] No
```
=> RIA-6134 appellant FTPA decision not admitted/refused

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaApplicationDecisionPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantFtpaApplicationDecisionPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/utils/FtpaNotificationPersonalisationUtil.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantFtpaApplicationDecisionPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantFtpaApplicationDecisionPersonalisationSmsTest.java
[RIA-6134](https://tools.hmcts.net/jira/browse/RIA-6134)
- Format due date in notifications
```
[ ] Yes
[x] No
```
=> RIA-6134 Write out due date in notifications that need it

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/MapValueExpander.java, src/functionalTest/resources/scenarios/RIA-3220-send-appeal-submitted-payment-pending-notification-legal-rep.json, src/functionalTest/resources/scenarios/RIA-6682-send-appeal-submitted-with-remission-pa-appeal-type-notification.json
https://tools.hmcts.net/jira/browse/RIA-6560
Updates to allow functional tests to run on windows machines.
```
[ ] Yes
[x] No
```
=> RIA-6560 - Functional tests improvement

Dockerfile, Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-1976-case-listed-notification-glasgow-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-1976-edit-case-listing-notification-glasgow-hearing-centre.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerChangeHearingCentrePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerChangeHearingCentrePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerEditListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
[
](https://tools.hmcts.net/jira/browse/RIA-5944)
```
[ ] Yes
[ ] No
```
=> RIA-5944 notification address update for CO

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationPersonalisationSms.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantDecideAnApplicationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantDecideAnApplicationPersonalisationSmsTest.java
[RIA-6952](https://tools.hmcts.net/jira/browse/RIA-6952)
- Edited notifications sent to appellant during AIP journey (used phrasing instead of the crude application type name) for notifications send when applications submitted by HO are decided
```
[ ] Yes
[x] No
```
=> RIA-6952 Edit notifications to AIP for HO application decisions

config/owasp/suppressions.xml
=> CVEs suppressions

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6629
* Created 2 new templates for appeal ended (before/after listing) with the updated content
* Updated yaml file to point to the 2 new templates for endAppeal
```
[ ] Yes
[X] No
```
=> RIA-6629 appeaEnded LR notifications content change

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecisionWithoutHearingPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecisionWithoutHearingPersonalisationTesting.java
https://tools.hmcts.net/jira/browse/RIA-6980
-Add the link for iaExUiFrontendUrl
-Update the unit test
```
[ ] Yes
[X] No
```
=> RIA-6980 HO notification when appeal is decided without hearing v2

src/functionalTest/resources/scenarios/RIA-6974-send-home-office-non-standard-direction-sms.json, src/functionalTest/resources/scenarios/RIA-6974-send-home-office-non-standard-direction.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNonStandardDirectionOfHomeOfficePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
=> RIA-6947 QA Fixes

audit.json
RIA-5679
ZAProxy suppressions
```
[ ] Yes
[x] No
```
=> RIA-5679 Partial fixes for nightly builds pipeline

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7105
```
[ ] Yes
[x] No
```
=> RIA-7105: Fix issue with NSD notifications to Home Office

src/functionalTest/resources/scenarios/RIA-7146-non-standard-direction-to-appellant-and-respondent-aip-after-listing.json, src/functionalTest/resources/scenarios/RIA-7146-non-standard-direction-to-appellant-and-respondent-aip-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNonStandardDirectionOfHomeOfficePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantNonStandardDirectionOfHomeOfficePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNonStandardDirectionOfHomeOfficePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantNonStandardDirectionOfHomeOfficePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7146
```
[ ] Yes
[x ] No
```
=> RIA-7146 NSD Notifications to the Appellant & Respondent

src/functionalTest/resources/scenarios/RIA-6974-send-home-office-non-standard-direction-sms.json, src/functionalTest/resources/scenarios/RIA-6974-send-home-office-non-standard-direction.json, src/functionalTest/resources/scenarios/RIA-7105-non-standard-direction-to-appellant-aip-after-listing.json, src/functionalTest/resources/scenarios/RIA-7105-non-standard-direction-to-appellant-aip-before-listing.json, src/functionalTest/resources/scenarios/RIA-7146-non-standard-direction-to-appellant-and-respondent-aip-after-listing.json, src/functionalTest/resources/scenarios/RIA-7146-non-standard-direction-to-appellant-and-respondent-aip-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7188
* Disable non standard direction to AIP
```
[ ] Yes
[x] No
```
=> RIA-7188: Disable non FTPA features (For FTPA release preparation)

src/functionalTest/resources/scenarios/RIA-7146-non-standard-direction-to-appellant-and-respondent-aip-after-listing.json, src/functionalTest/resources/scenarios/RIA-7146-non-standard-direction-to-appellant-and-respondent-aip-before-listing.json
https://tools.hmcts.net/jira/browse/RIA-7146
```
[ ] Yes
[x] No
```
=> RIA-7146: Fix issue in functional tests

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAdaSuitabilityReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamFtpaSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHearingBundleReadyPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestCaseBuildingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRespondentFtpaApplicationDecidedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRespondentReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUploadAppealResponsePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/OtherDetentionEngagementTeamFtpaSubmittedPersonalisation.java
=> Fix for Sonar check on jenkins pipeline

src/functionalTest/resources/scenarios/RIA-7118-update-detention-location-legal-rep-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-7118-update-detention-location-legal-rep-notification-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/OtherDetentionFacilityName.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateDetentionLocationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateDetentionLocationPersonalisationTest.java
=> RIA-7118: Added LR notification for 'Update Detention Location' Event

config/owasp/suppressions.xml, src/functionalTest/resources/templates/minimal-appeal-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerPersonalisationProvider.java
=> Fix username on functional tests after IDAM change

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java
https://tools.hmcts.net/jira/browse/RIA-7174
- Adding new document tag to the list and unit test
```
[ ] Yes
[X] No
```
=> RIA-7174 Adding new document tag

src/functionalTest/resources/scenarios/RIA-6782-hearing-bundle-is-ready-notification-to-det-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHearingBundleReadyPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHearingBundleReadyPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7199
* Updating hearing bundle ready notification
* Added notification subject prefixes for internal cases to yaml file
```
[ ] Yes
[X] No
```
=> Ria 7199 hearing bundle ready notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAdaSuitabilityReviewPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAdaSuitabilityReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7173
- Fix subject prefix 'ADA - SERVE IN PERSON' value
```
[ ] Yes
[X] No
```
=> RIA-7173 Fix notification subject prefix

src/functionalTest/resources/scenarios/RIA-7211-internal-ada-appeal-decided-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealDecidedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealDecidedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7211
Added appeal decided - ADA notifications, email templates, tests.
```
[ ] Yes
[x ] No
```
=> RIA-7211_appeal_decided_notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/DetEmailService.java
https://tools.hmcts.net/jira/browse/RIA-7528
- Remove redundant regex expression
- Added isPresent check
```
[ ] Yes
[X] No
```
=> RIA-7528 DetEmailService fix sonar issues

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHearingBundleFailedPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHearingBundleFailedPersonalisationTest.java
RIA-7639
Minor improvement to logging of failed bundle generation
```
[ ] Yes
[x] No
```
=> RIA-7639 Improve logging on failed bundle generation notifications

charts/ia-case-notifications-api/Chart.yaml, src/functionalTest/resources/scenarios/RIA-7547-internal-appeal-submission-non-ada-in-time-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedInTimePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAppealSubmittedInTimePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7547
Add Non-ada, detained only, in-Time, internal submitted appeal Personalisation, Handler and generator configurations, tests.
```
[ ] Yes
[x ] No
```
=> RIA-7547_internal_appeal_submitted

src/functionalTest/resources/scenarios/RIA-7214-internal-detained-appeal-decided-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealDecidedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealDecidedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7214
Updated config to handle detained non ADA notification
```
[ ] Yes
[ x ] No
```
=> RIA-7214 Updated config to handle detained non ADA notification

build.gradle, config/owasp/suppressions.xml
RIA-7723
Upgrade libraries to solve vulnerabilities
```
[ ] Yes
[x] No
```
=> RIA-7723 Solve suppressions

src/functionalTest/resources/scenarios/RIA-7558-internal-detained-non-ada-case-listed.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamListCasePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7558
Added notification for internal detained list case event
```
[ ] Yes
[ x ] No
```
=> RIA-7558 Added notification for internal detained list case event

src/functionalTest/resources/scenarios/RIA-7371-internal-ada-end-appeal-notification.json, src/functionalTest/resources/scenarios/RIA-7371-internal-non-ada-end-appeal-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamEndAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealDecidedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamEndAppealAutomaticallyPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamEndAppealPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7371
https://tools.hmcts.net/jira/browse/RIA-7672
Added for Internal ada and non-ada End appeal event:
Personalisation, Handler and Generator configurations, functional tests, junit tests
```
[ ] Yes
[ x] No
```
=> RIA-7371 RIA-7672 internal end appeal

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisationTest.java
=> RIA-7363 Fix Sonar bug

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7559
suppress notif to LR for list case event for internal cases
```
[ ] Yes
[X] No
```
=> RIA-7559 suppress notif to LR for list case event for internal cases

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerPersonalisationProvider.java
Merged Master changes to Naba notifications
```
[ ] Yes
[x] No
```
=> RIA-TASK - Merged Master changes to NABA notifications

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-7698-internal-detained-transferred-out-of-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamTransferOutOfAdaPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamTransferOutOfAdaPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7698
Added internal detained transfer out of ada notification
```
[ ] Yes
[ x ] No
```
=> RIA-7698 Added internal detained transfer out of ADA notification

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, charts/ia-case-notifications-api/values.yaml, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-7864
Added IA admin email for harmondsworth and yarlswood
```
[ ] Yes
[ x ] No
```
=> RIA-7864 Added IA admin email for harmondsworth and yarlswood

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppellantFtpaDecidedByResidentJudgePersonalisation.java
https://tools.hmcts.net/jira/browse/RIA-7329
https://tools.hmcts.net/jira/browse/RIA-7676
* Refactored how link for iaut1 form is built into template content
```
[ ] Yes
[X] No
```
=> RIA-7329 RIA-7676 Refactored how link for iaut1 form is built into template content

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, charts/ia-case-notifications-api/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7873
* Added yarlwood to application.yaml homeOfficeFtpaEmailAddresses section
* Updated jenkins files
* Updated values.yaml and README.md
```
[ ] Yes
[X] No
```
=> RIA-7873 Added yarlwood to homeOfficeFtpaEmailAddresses map

src/functionalTest/resources/scenarios/RIA-7321-internal-update-hearing-requirements-ada-notification.json, src/functionalTest/resources/scenarios/RIA-7689-internal-update-hearing-requirements-non-ada-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUpdateHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUpdateHearingRequirementsPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7321 - ADA
https://tools.hmcts.net/jira/browse/RIA-7689 - Non-ADA
- Sending notification to DET for ADA and Non-ADA scenarios where the event 'Update hearing requirements' is triggered by Judge/LO
- Unit and functional tests
```
[ ] Yes
[X] No
```
=> RIA-7321 RIA-7689 Internal DET notification for update hearing reqs

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7896
* Added !isInternalCase check to 2 handlers to prevent email being sent to LR for internal case
```
[ ] Yes
[X] No
```
=> RIA-7896 callback error when LO send direction to respondent

src/functionalTest/resources/scenarios/RIA-7375-internal-ada-maintain-case-link-appeal-notification.json, src/functionalTest/resources/scenarios/RIA-7694-internal-non-ada-maintain-case-link-appeal-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamMaintainCaseLinkAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamMaintainCaseLinkAppealPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7375
https://tools.hmcts.net/jira/browse/RIA-7694
- Added functionality to send notification for an appealant application when cases linked
- Added/updated unit/FTs
```
[ ] Yes
[x ] No
```
=> RIA-7375 RIA-7694 link_case

src/functionalTest/resources/scenarios/RIA-7426-internal-upload-additional-evidence-det-notification-ada.json, src/functionalTest/resources/scenarios/RIA-7692-internal-upload-additional-evidence-det-notification-non-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUploadAdditionalEvidencePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUploadAdditionalEvidencePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7426 - ADA
https://tools.hmcts.net/jira/browse/RIA-7692 - Non-ADA
- Notification to DET for ADA and Non-ADA scenarios when triggering 'Upload additional evidence' for internal cases
- Unit tests
- Functional tests
```
[ ] Yes
[X] No
```
=> RIA-7426 RIA-7692 Upload additional evidence DET notification

src/functionalTest/resources/scenarios/RIA-7436-internal-detained-non-standard-direction-appellant-notification.json, src/functionalTest/resources/scenarios/RIA-7436-internal-detained-non-standard-direction-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamNonStandardDirectionPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestHearingRequirementsPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamInternalNonStandardDirectionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7437
updating doc tags to match case docs
```
[ ] Yes
[x ] No
```
=> RIA-7437 Updating document tag to match case-docs tag

src/functionalTest/resources/scenarios/RIA-7691-internal-upload-addendum-evidence-admin-officer-det-notification-ada.json, src/functionalTest/resources/scenarios/RIA-7693-internal-upload-addendum-evidence-admin-officer-det-notification-non-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUploadAddendumEvidenceAdminOfficerPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUploadAddendumEvidenceAdminOfficerPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7691 - ADA
https://tools.hmcts.net/jira/browse/RIA-7693 - Non-ADA
- Notification to DET for event 'Upload addendum evidence Admin Officer'
- Unit tests
- Functional tests
```
[ ] Yes
[X] No
```
=> RIA-7691 RIA-7693 Notification for upload addendum evidence AO

src/functionalTest/resources/scenarios/RIA-7432-internal-detained-ada-change-hearing-centre.json, src/functionalTest/resources/scenarios/RIA-7690-internal-detained-change-hearing-centre.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamChangeHearingCentrePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamChangeHearingCentrePersonalisationTest.java
- RIA-7690
- For detained and ADA appeals
```
[ ] Yes
[x] No
```
=> RIA-7432 Send DET notifications when LO changes the hearing centre

src/functionalTest/resources/scenarios/RIA-7369-internal-ada-home-office-upload-additional-evidence-det-notification.json, src/functionalTest/resources/scenarios/RIA-7466-internal-ada-home-office-upload-addendum-evidence-det-notification.json, src/functionalTest/resources/scenarios/RIA-7709-internal-detained-home-office-upload-additional-evidence-det-notification.json, src/functionalTest/resources/scenarios/RIA-7710-internal-detained-home-office-upload-addendum-evidence-det-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHomeOfficeUploadAdditionalAddendumEvidencePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHomeOfficeUploadAdditionalAddendumEvidencePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7466
https://tools.hmcts.net/jira/browse/RIA-7710
https://tools.hmcts.net/jira/browse/RIA-7369
https://tools.hmcts.net/jira/browse/RIA-7709
* Imported new doc tags from docs-api
* Added new personalisation for HO upload additional/addendum evidence
* Added new generator and handler beans for same
* Added/updated unit/FTs
=> RIA-7466 RIA-7710 RIA-7369 RIA-7709 HO uploads additional/addendum evidence detained/ADA notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java
RIA-7443 RIA-7711 Sonar fix optional.isEmpty/isPresent check
=> RIA-7443 RIA-7711 Sonar fix optional.isEmpty/isPresent check

.github/workflows/pr-title-validation.yml, build.gradle
=> DIAC-000 Dependency fix

.github/workflows/swagger.yml
=> DIAC-000 update swagger test pointing name

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7537
Additional role access being given to Legal officer for EJP cases
- [x ] Does this PR introduce a breaking change
=> RIA-7537 EJP LO additional events

.github/renovate.json
https://tools.hmcts.net/jira/browse/DIAC-2
Updating config options for renovate
=> DIAC-2 adding renovate config option for exclusion of major updates

charts/ia-case-notifications-api/Chart.yaml, config/owasp/suppressions.xml
Upgraded java chart version to 5.0.0
=> RIA-8888 Upgraded java chart version to 5.0.0

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-7544-internal-detained-mark-appeal-paid-notifications-non-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsPaidPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsPaidPersonalisationTest.java
adding notification to be sent to home office when admin/LO mark an appeal as paid for. For admin created non ADA case.
https://tools.hmcts.net/jira/browse/RIA-7947
- [x ] Does this PR introduce a breaking change
=> RIA-7947 Adding notification for Appeal Submitted

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-7948-internal-ada-submit-appeal-notification.json, src/functionalTest/resources/scenarios/RIA-7948-internal-non-ada-submit-appeal-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7948
Added missing HO notification and testing-related
=> RIA-7948 name_of_branch

src/functionalTest/resources/scenarios/RIA-7516-internal-detained-request-respondent-evidence-notifications-ejp.json, src/functionalTest/resources/scenarios/RIA-7516-internal-request-respondent-evidence-notifications-ejp.json, src/functionalTest/resources/templates/minimal-ejp-appeal-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentEvidenceDirectionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRequestHearingRequirementsPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentEvidenceDirectionPersonalisationTest.java
- Updated unit test and added functional test.
=> RIA-7516 Update notification to HO when LO triggers requestRespondentEvidence for an EJP appeal

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7882
RIA-7882 Add editCaseListing permission for caseworker-ia-system
=> RIA-7882 Add editCaseListing permission for caseworker-ia-system

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/RIA-7734_ho_apply_for_costs_respondent_notification.json, src/functionalTest/resources/scenarios/RIA-7734_legalrep_apply_for_costs_respondent_notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ApplyForCosts.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsRespondentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7734
Added Notification template for respondent when 'Apply for costs' triggered. Added tests, FT tests and configurations for new HO email address as well
=> RIA-7734 apply_for_costs_respondent_notification

Jenkinsfile_nightly, build.gradle, charts/ia-case-notifications-api/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DIAC-117
=> DIAC-117 adding smoke, unit, integration testing and easy access reports to nightly build

src/functionalTest/resources/scenarios/RIA-7661-turn-on-notifications-HO-after-listing.json, src/functionalTest/resources/scenarios/RIA-7661-turn-on-notifications-HO-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentTurnOnNotificationsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentTurnOnNotificationsPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7661
Added code functionality and test scenarios
=> RIA-7661 Appeal transferred to the First-tier Tribunal - HO notification

src/functionalTest/resources/scenarios/RIA-7929-internal-ada-decided-without-hearing-ho.json, src/functionalTest/resources/scenarios/RIA-7929-internal-non-ada-decided-without-hearing-ho.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7929
Added missing HO notification and functional test scenarios
=> RIA-7929 Decision without a hearing - Existing HO notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeNotificationsTurnedOnPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeNotificationsTurnedOnPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7662
Changes to allow 16 digit reference number to be accessed for Turn On Notification LR event
=> RIA-7622 updating new 16 digit reference field

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7950
Added to 'makeAnApplication' and 'removeAppealFromOnline' in 'NotificationGeneratorConfiguration.class' conditions that it is only LegalRep journeys.
=> RIA-7950 refactor_existing_notification

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeEmailNotificationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeForceCaseProgressionToCaseUnderReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentForceCaseToCaseUnderReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeForceCaseProgressionToCaseUnderReviewPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentForceCaseToCaseUnderReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-5739
Cleaner PR for https://github.com/hmcts/ia-case-notifications-api/pull/658
```
[ ] Yes
[x] No
```
=> RIA-5739 Force case event for Case Building to Case Under Review

src/functionalTest/resources/scenarios/RIA-2774-force-case-progression-notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_ho_respond_to_costs_notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_legalrep_respond_to_costs_notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsApplicantPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/RespondToCostsApplicantPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/RespondToCostsRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsApplicantPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsRespondentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7794, https://tools.hmcts.net/jira/browse/RIA-7796
Fixed the **applicationId** value get method for Notification template.
=> RIA-7794 respond_to_costs_notification_fix

src/functionalTest/resources/scenarios/RIA-7434-RIA-7930-internal-detained-non-standard-direction-to-ho-notification.json, src/functionalTest/resources/scenarios/RIA-7436-RIA-7930-internal-detained-non-standard-direction-appellant-notification.json, src/functionalTest/resources/scenarios/RIA-7436-RIA-7930-internal-detained-non-standard-direction-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7930
Added missing HO notification and func test updated
=> RIA-7930 NSD to appellant

src/functionalTest/resources/scenarios/RIA-7733-RIA-7734_ho_apply_for_costs_respondent_notification.json, src/functionalTest/resources/scenarios/RIA-7733-RIA-7734_legalrep_apply_for_costs_respondent_notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ApplyForCosts.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsApplicantPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/DateUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsApplicantPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ApplyForCostsRespondentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/RespondToCostsApplicantPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/RespondToCostsRespondentPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/DateUtilsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7734
https://tools.hmcts.net/jira/browse/RIA-7733
Changed 'Application name' field in template to 'Date application was made:'. Edited Junit, FT tests as well. Added utils for date converting.
=> RIA-7733 template_field_change_v2

src/functionalTest/resources/scenarios/RIA-7375-RIA-7928-internal-ada-maintain-case-link-appeal-notification.json, src/functionalTest/resources/scenarios/RIA-7377-RIA-7928-internal-ada-maintain-case-unlink-appeal-notification.json, src/functionalTest/resources/scenarios/RIA-7694-RIA-7928-internal-non-ada-maintain-case-link-appeal-notification.json, src/functionalTest/resources/scenarios/RIA-7695-RIA-7928-internal-non-ada-maintain-case-lists-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7928
Added missing HO notification and updated functional test scenarios
=> RIA-7928 Link/Unlink appeal

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationSms.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantForceCaseProgressionToCaseUnderReviewPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/DIAC-164
=> DIAC-164 fixing correct appeal notifications

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7969
give system user permission to sendBailDirection
=> RIA-7969 give system user permission to sendBailDirection

src/functionalTest/resources/scenarios/bail/RIA-8112-HO-upload-bail-summary-direction-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeUploadBailSummaryDirectionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeUploadBailSummaryDirectionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8112
Send HO upload bail summary notification
=> RIA-8112 - Send HO upload bail summary notification

src/functionalTest/resources/scenarios/RIA-8179-re-list-case-with-integrated-case-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8179
RIA-8179 Send relistCaseNotification only when case is not integrated.
=> RIA-8179 Send relistCaseNotification only when case is not integrated.

src/functionalTest/resources/scenarios/RIA-7733-RIA-7734_ho_apply_for_costs_respondent_notification.json, src/functionalTest/resources/scenarios/RIA-7733-RIA-7734_legalrep_apply_for_costs_respondent_notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_ho_respond_to_costs_notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_legalrep_respond_to_costs_notification.json, src/functionalTest/resources/scenarios/RIA-7812_consider_making_costs_order_notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ConsiderMakingCostOrderHoPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ConsiderMakingCostOrderLegalRepPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ConsiderMakingCostOrderHoPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/ConsiderMakingCostOrderLegalRepPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7812
Added "Consider making a cost order" event. ConsiderMakingCostOrderHoPersonalisation and ConsiderMakingCostOrderLegalRepPersonalisation, Configuration for notifications, authorisations and templates for current emails. Junit and FT tests. As well fixed existing FT headers from "Home office reference" to "Home Office reference", fixed junit test related to it and personalisationProvider method.
=> RIA-7812 consider_costs_order

src/functionalTest/resources/scenarios/RIA-7807_HO_additional_evidence_to_costs_notification_submitter.json, src/functionalTest/resources/scenarios/RIA-7807_LR_additional_evidence_to_costs_notification_submitter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/AddEvidenceForCostsSubmittedSubmitterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/AddEvidenceForCostsSubmittedSubmitterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7807
Added personalisation and testing
=> RIA-7807 Additional evidence submitted - Submitter Notification

Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/DIAC-109
=> DIAC-109 turning on fortify

src/functionalTest/resources/scenarios/bail/RIA-8349-RIA-8352-send-bail-relisting-case-listing-notifications.json
https://tools.hmcts.net/jira/browse/RIA-8352
Notifications for Bail Listing (relisting) were updated on Govnotify so updating them here in the functional tests
=> RIA-8349 RIA-8352 Updated notification subjects for relisting FTs

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsRespondentAndApplicantPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsRespondentAndApplicantPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7810
decide costs class rename refactor due to miss-spelling
=> RIA-7810 decide costs rename refactor

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailHearingLocation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailHearingLocationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-8455
- Updated the location list in notification API
- Updated related the unit test
=> RIA-8455 locations on case listing event are correct

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle, charts/ia-case-notifications-api/values.yaml, src/functionalTest/resources/scenarios/bail/RIA-8198-decision-under-ima-notification-ut.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/BailCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RecordDecisionType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailSignedDecisionNoticeUploadedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalDecisionRefusedImaPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RecordDecisionTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalDecisionRefusedImaPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationGeneratorTest.java
https://tools.hmcts.net/jira/browse/RIA-8198
Decision Refused under IMA - Notification to UT
- [x ] tests have been updated / new tests has been added (if needed)
=> RIA-8198 - Decision Refused under IMA - Notification to UT

src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications-not-legally-represented.json, src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalApplicationEndedImaPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalApplicationEndedImaPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8454
Created notification for UT if application has IMA and was ended.
=> RIA-8454 end_app_ut_notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7759
Hearing update displays which adjustments have been granted
=> RIA-7759 - Hearing update displays which adjustments have been granted

src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications-not-legally-represented.json, src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java
Updated the condition when the notification should be sent to UT when the application is ended.
=> RIA-8195 ima_showing_condition_fix

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8198
Added to admin roleevent 'record the decision' event
=> RIA-8198 fix_authorisations

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalDecisionRefusedImaPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalDecisionRefusedImaPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8198
Fixed text line in the template for Refused cases
=> RIA-8198 refused_notification

src/functionalTest/resources/scenarios/RIA-8160-decide-ftpa-under-rule-31-notification-appellant.json, src/functionalTest/resources/scenarios/RIA-8160-decide-ftpa-under-rule-32-notification-respondent.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeFtpaApplicationDecidedRule31Rule32Personalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeFtpaApplicationDecidedRule31Rule32Personalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeFtpaApplicationDecidedRule31Rule32PersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeFtpaApplicationDecidedRule31Rule32PersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8160
Decide FTPA application rule31 rule32 notifications
=> RIA-8160 Decide FTPA application rule31 rule32 notifications

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatus.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelper.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/field/PaymentStatusTest.java
https://tools.hmcts.net/jira/browse/DIAC-195
=> DIAC-195 updating PaymentStatus.java to match case api

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ApplyForCosts.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProvider.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/PersonalisationProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7809
RIA-7809 - Fix for missing respondToCostsList error
=> RIA-7809 - Fix for missing respondToCostsList error

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8203
Added condition to ftpaApplicationDecisionReheardAppellantNotificationHandler !isDlrmSetAsideEnabled(asylumCase)
=> RIA-8203 add_toggler_condition

src/functionalTest/resources/scenarios/RIA-8505-FTPA set aside to be reheard under rule 35 - HO Notification.json, src/functionalTest/resources/scenarios/RIA-8505-FTPA set aside to be reheard under rule 35 appellant - HO Notification.json, src/functionalTest/resources/scenarios/RIA-8505-FTPA set aside to be reheard under rule 35 respondent- HO Notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentReheardUnderRule35PersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentReheardUnderRule35PersonalisationEmailTest.java
https://tools.hmcts.net/jira/browse/RIA-8505
Implementation and testing
=> RIA-8505 Implementation and testing

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNotificationsTurnedOnPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNotificationsTurnedOnPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNotificationsTurnedOnPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantNotificationsTurnedOnPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-7664
Appeal transferred to First-tier Tribunal - Unrepresented Appellant notification
=> RIA-7664 - Appeal transferred to First-tier Tribunal - Unrepresented Appellant notification

src/functionalTest/resources/scenarios/RIA-7810_Judge_Decide_a_Costs_notifications_to_HO_and_LR.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsHomeOfficePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsLegalRepPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsHomeOfficePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsLegalRepPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7810
Decides Costs notifiation to LR and HO headers update
- [ x] commit messages are meaningful and follow good commit message guidelines
=> RIA-7810 - Decides Costs notifiation to LR and HO headers update

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailEmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/SmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelper.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelperTest.java
https://tools.hmcts.net/jira/browse/DIAC-207
When SMS notification fails, skip the failed notification and complete the event
=> DIAC-207 Skip failed SMS notifications

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-with-remission-aip-notification-dlrm-feature-flag-disabled.json, src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-with-remission-aip-notification-with-dlrm-feature-flag-enabled.json, src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-with-remission-aip-notification-without-remission-and-dlrm-feature-flag-enabled.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RemissionOption.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8053
RIA-8053 Modify remissionType to remissionOption to integrate with Aip
=> RIA-8053 Modify remissionType to remissionOption to integrate with Aip

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RIA-7807
Suppress CVE
=> RIA-7807 - Suppress CVE

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications-not-legally-represented.json, src/functionalTest/resources/scenarios/bail/RIA-5214-send-application-ended-notifications.json, src/functionalTest/resources/scenarios/bail/RIA-8198-decision-under-ima-notification-ut.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/BailCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RecordDecisionType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailSignedDecisionNoticeUploadedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalApplicationEndedImaPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalDecisionRefusedImaPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/RecordDecisionTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalApplicationEndedImaPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/uppertribunal/UpperTribunalDecisionRefusedImaPersonalisationTest.java
=> RIA-TASK - IMA -> Master: DO NOT MERGE

src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-revocation-of-protection-with-no-remission-aip-notification-with-dlrm-feature-flag-enabled.json, src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-revocation-of-protection-with-no-remission-out-of-time-aip-notification-with-dlrm-feature-flag-enabled.json, src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-revocation-of-protection-with-remission-aip-notification-with-dlrm-feature-flag-enabled.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8053
RIA-8053 filter notifications when appeal without remission is created
=> RIA-8053 filter notifications when appeal without remission is created

src/functionalTest/resources/scenarios/RIA-8243-update-tribunal-decision-r31-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateTribunalDecisionRule31PersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentUpdateTribunalDecisionRule31PersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateTribunalDecisionRule31PersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentUpdateTribunalDecisionRule31PersonalisationEmailTest.java
https://tools.hmcts.net/jira/browse/RIA-8243
Update Tribunal Decision R31 Notification
=> RIA-8243 Update Tribunal Decision R31 Notification

src/functionalTest/resources/scenarios/RIA-8221-update-tribunal-decision-r32-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateTribunalDecisionRule32PersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentUpdateTribunalDecisionRule32PersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateTribunalDecisionRule32PersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentUpdateTribunalDecisionRule32PersonalisationEmailTest.java
https://tools.hmcts.net/jira/browse/RIA-8221
Update Tribunal Decision R32 NOTIF
=> RIA-8221 Update Tribunal Decision R32 NOTIF

Jenkinsfile_nightly, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/CcdScenarioRunnerTest.java, src/functionalTest/resources/scenarios/RIA-4559-reinstate-appeal-notification-after-listing-aip.json
https://tools.hmcts.net/jira/browse/DIAC-281
=> DIAC-281 fixing CcdScenarioRunnerTest

src/functionalTest/resources/scenarios/RIA-8722-decide-ftpa-appellant-under-rule-35-notifications-legal-rep-and-home-office.json, src/functionalTest/resources/scenarios/RIA-8722-decide-ftpa-respondent-under-rule-35-notifications-legal-rep-and-home-office.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeReheardUnderRule35Personalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeReheardUnderRule35PersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8722
- New template to include different header replacing HO Reference Number with LR Reference Number
- Passing this value in Personalisation class
- Unit and functional test updated
=> RIA-8722 QA fixes - replace HO Reference with LR Reference

src/functionalTest/resources/scenarios/RIA-8218-update-tribunal-decision-r31-aip-notification-both-document-decision.json, src/functionalTest/resources/scenarios/RIA-8218-update-tribunal-decision-r31-aip-notification-decision.json, src/functionalTest/resources/scenarios/RIA-8218-update-tribunal-decision-r31-aip-notification-document.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantUpdateTribunalDecisionRule31PersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantUpdateTribunalDecisionRule31PersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/utils/UpdateTribunalDecisionRule31PersonalisationUtil.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantUpdateTribunalDecisionRule31PersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantUpdateTribunalDecisionRule31PersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/utils/UpdateTribunalDecisionRule31PersonalisationUtilTest.java
https://tools.hmcts.net/jira/browse/RIA-8218
Added AIP notifications for update tribunal decision event rule 31
=> RIA-8218 Added AIP notifications for rule 31

build.gradle
[VUL-5809](https://tools.hmcts.net/jira/browse/VUL-5809)
- Upgraded serenity to 4.1.3
- Upgraded restAssured to 5.4.0
- Removed unused reference to springHystrix
=> RIA-TASK VUL-5809 Upgrade serenity, restAssured, remove springHystrix reference

src/functionalTest/resources/scenarios/RIA-8258-mark-appeal-as-remitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/SourceOfRemittal.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsRemittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMarkAppealAsRemittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsRemittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMarkAppealAsRemittedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8258
Mark appeal as remitted - Notification to LR/HO
=> RIA-8258 - Mark appeal as remitted Notification to LR/HO

src/functionalTest/resources/scenarios/RIA-8258-mark-appeal-as-remitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/SourceOfRemittal.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsRemittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMarkAppealAsRemittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsRemittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMarkAppealAsRemittedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8258
Mark appeal as remitted - Notification to LR/HO
=> RIA-8258 - Mark appeal as remitted - Notification to LR/HO

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/testutils/SpringBootIntegrationTest.java
[VUL-5808](https://tools.hmcts.net/jira/browse/VUL-5808)
- Removed exposed credentials
=> RIA-TASK VUL-5808 Remove credentials from SpringBootIntegrationTest

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/SourceOfRemittal.java
https://tools.hmcts.net/jira/browse/RIA-8257
Updated SourceOfRemittal value
=> RIA-8257 Updated SourceOfRemittal value

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java
=> RIA-8254 Added new state in the State Enum 'remitted'

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8069
https://tools.hmcts.net/jira/browse/RIA-8070
Added security role, and Non-aip check for existing notification handler for Ask for a fee remission journey.
=> RIA-8069_RIA-8070 ask_for_fee_remission

src/functionalTest/resources/scenarios/RIA-8062-mark-appeal-as-paid-with-remission-aip-notification-with-dlrm-fee-remission-feature-flag-enabled.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmittedWithRemissionMarkAppealAsPaidPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmittedWithRemissionMarkAppealAsPaidPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantSubmittedWithRemissionMarkAppealAsPaidPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantSubmittedWithRemissionMarkAppealAsPaidPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-8062
RIA-8062 Create mark appeal as paid Aip notification
=> RIA-8062 Create mark appeal as paid Aip notification

src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/CcdScenarioRunnerTest.java, src/functionalTest/resources/scenarios/RIA-4559-reinstate-appeal-notification-after-listing-aip.json, src/functionalTest/resources/scenarios/RIA-8053-appeal-submitted-with-remission-aip-notification-with-dlrm-feature-flag-enabled.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-appellant-reheard-after-respondent-granted-bradford-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-appellant-reheard-after-respondent-granted-taylor-house-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-allowed-respondent-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-appellant-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-r32-respondent-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-respondent-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-rule-32-appellant-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-rule-32-respondent-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-rule-35-appellant-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-applicant-appeal-decision-reheard-rule-35-respondent-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-respondent-reheard-after-appellant-refused-glasgow-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-respondent-reheard-after-appellant-refused-taylor-house-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8101-ftpa-submitted-respondent-granted-after-appellant-granted-decide-ftpa-application.json, src/functionalTest/resources/scenarios/RIA-8184-decide-ftpa-under-rule-31-32-appellant-notification.json, src/functionalTest/resources/scenarios/RIA-8184-decide-ftpa-under-rule-31-32-respondent-notification.json, src/functionalTest/resources/scenarios/RIA-8203-ftpa-set-aside-to-be-reheard-under-rule-35-aip-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8758
- CcdScenarioRunnerTest changes rebased from master
- Draft to run functional tests on pipeline
**Functional test changes:**
RIA-2975-RIA-3003-RIA-3754 FTPA Applic****nt Applic****tion Decision Allowed Appell****nt (T****ylor House he****ring centre);
RIA-2975-RIA-3003-RIA-3754 FTPA Applic****nt Applic****tion Decision Allowed Respondent (M****nchester he****ring centre);
RIA-2975-RIA-3003-RIA-3754 FTPA Applic****nt Applic****tion Decision Dismissed Appell****nt (M****nchester he****ring centre);
RIA-2975-RIA-3003-RIA-3754 FTPA Applic****nt Applic****tion Decision Dismissed Respondent (Gl****sgow he****ring centre);
RIA-2975-RIA-3003-RIA-3754 FTPA Applic****nt Applic****tion Decision Not Admitted Appell****nt (Br****dford he****ring centre); …
=> RIA-8758 fix func tests patch

src/functionalTest/resources/scenarios/RIA-8184-decide-ftpa-under-rule-31-32-appellant-notification.json, src/functionalTest/resources/scenarios/RIA-8184-decide-ftpa-under-rule-31-32-respondent-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8766
Added HO email to AIP journey for remadeRule31 and remadeRule32 outcome
=> RIA-8766 Added HO email to AIP journey for remadeRule31 and remadeRule32 outcome

src/functionalTest/resources/scenarios/RIA-8203-ftpa-set-aside-to-be-reheard-under-rule-35-aip-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8765
Added rule 35 HO notification to AIP journey
=> RIA-8765 Added rule 35 HO notification to AIP journey

src/functionalTest/resources/scenarios/RIA-4559-unlink-appeal-after-listing-notification-aip.json, src/functionalTest/resources/scenarios/RIA-7323-internal-non-ada-adjourn-hearing-without-date-notification.json, src/functionalTest/resources/scenarios/RIA-7329-internal-appellant-ftpa-rj-decided-ada-granted.json, src/functionalTest/resources/scenarios/RIA-7662-7663-turn-on-notifications-lr-and-appellant-after-listing.json, src/functionalTest/resources/scenarios/RIA-7662-7663-turn-on-notifications-lr-and-appellant-before-listing.json, src/functionalTest/resources/scenarios/RIA-7733-RIA-7734_ho_apply_for_costs_respondent_notification.json, src/functionalTest/resources/scenarios/RIA-7733-RIA-7734_legalrep_apply_for_costs_respondent_notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_ho_respond_to_costs_notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_legalrep_respond_to_costs_notification.json, src/functionalTest/resources/scenarios/RIA-7808_HO_additional_evidence_to_costs_notification_other_party.json, src/functionalTest/resources/scenarios/RIA-7808_LR_additional_evidence_to_costs_notification_other_party.json, src/functionalTest/resources/scenarios/RIA-7810_Judge_Decide_a_Costs_notifications_to_HO_and_LR.json, src/functionalTest/resources/scenarios/RIA-7958_internal_appelant_ftpa_partially_granted_ada.json, src/functionalTest/resources/scenarios/RIA-8602-internal-non-detained-submit-appeal-notification.json
=> RIA-TASK - Fix failed functional tests

src/functionalTest/resources/scenarios/RIA-3690-8063-remission-decision-partially-approved.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionPartiallyApprovedPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRemissionDecisionPartiallyApprovedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8063
Remission partially approved - LR Notification (Email) - Update
=> RIA-8063 remission partially approved LR notification

src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AppealDecisionTest.java
=> RIA-1111 fix_build

build.gradle, src/functionalTest/resources/scenarios/RIA-8247-manage-fee-update-aip-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/FeeTribunalAction.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/FeeUpdateReason.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantManageFeeUpdatePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantManageFeeUpdatePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/utils/CommonUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantManageFeeUpdatePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantManageFeeUpdatePersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/utils/CommonUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-8247
Added Personalisations for "Manage fee update" for Sms and Email AiP notifications. Added junit and FT tests
=> RIA-8247 manage_fee_update

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java
=> RIA-TASK - Fix conflicts 3

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveRepresentationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentNonStandardDirectionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8819
Updated events to handle remitted state
=> RIA-8819 Updated events to handle remitted state

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisationTest.java
=> RIA-8807 Make an application event in the Remitted state

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/MakeAnApplicationService.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8626
Fixed Remitted state HO emails for decide application
=> RIA-8626 Fixed Remitted state HO emails for decide application

Jenkinsfile_nightly
=> RIA-TASK - Fix nightly tests

src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-initial-case-listing-notifications-with-ref-data-location.json, src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-initial-case-listing-notifications-with-remote-hearing.json, src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-relisting-case-listing-notifications-ref-data-location.json, src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-relisting-case-listing-notifications-remote-hearing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/model/refdata/CourtVenue.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-8803
- retrieve the listing location from reference data for 6 notification template
- create and update unit test
- create functional test
=> RIA-8803 bails notifications displays the correct location information SNL

src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-initial-case-listing-notifications-with-ref-data-location.json, src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-initial-case-listing-notifications-with-remote-hearing.json, src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-relisting-case-listing-notifications-ref-data-location.json, src/functionalTest/resources/scenarios/bail/RIA-8803-send-bail-relisting-case-listing-notifications-remote-hearing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/model/refdata/CourtVenue.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-8803
- retrieve the listing location from reference data for 6 notification template
- create and update unit test
- create functional test
=> RIA-8803 bails notifications displays the correct location information

src/functionalTest/resources/scenarios/RIA-7615-appeal-fee-is-due-det-notification-remission-rejected.json, src/functionalTest/resources/scenarios/RIA-7911-internal-update-hearing-adjustments-non-ada-notification.json, src/functionalTest/resources/scenarios/RIA-7948-internal-non-ada-submit-appeal-notification.json, src/functionalTest/resources/templates/minimal-internal-appeal-submitted.json
=> RIA-TASK - Fix nightly FTs

src/functionalTest/resources/scenarios/RIA-8061-aip-payment-reminder-remission-rejected.json, src/functionalTest/resources/scenarios/RIA-806100-aip-payment-reminder-remission-partiallyapproved.json, src/functionalTest/resources/scenarios/RIA-8160-decide-ftpa-under-rule-31-notification-appellant.json, src/functionalTest/resources/scenarios/RIA-8160-decide-ftpa-under-rule-32-notification-respondent.json, src/functionalTest/resources/scenarios/RIA-8184-decide-ftpa-under-rule-31-32-appellant-notification.json, src/functionalTest/resources/scenarios/RIA-8184-decide-ftpa-under-rule-31-32-respondent-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipRemissionRequestAutomaticReminderEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipRemissionRequestAutomaticReminderSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AiPRemissionRequestAutomaticReminderEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AiPRemissionRequestAutomaticReminderSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-8061
Payment Reminder - AiP Notification (Email/SMS)
=> RIA-8061 aip payment reminder remission

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/NotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/NotificationType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/LetterNotificationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/LetterNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/RetryableNotificationClient.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelper.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/RetryableNotificationClientTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelperTest.java
https://tools.hmcts.net/jira/browse/RIA-8297
- Adding implementation for GovNotify Letter notifications
=> RIA-8297 Send Letter notification type implementation

src/functionalTest/resources/scenarios/RIA-4712-aip-edit-listing-notification.json, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8941
=> RIA-8941 Fix issue with hearing address

src/functionalTest/resources/scenarios/RIA-7615-appeal-fee-is-due-det-notification-remission-rejected.json, src/functionalTest/resources/scenarios/RIA-7911-internal-update-hearing-adjustments-non-ada-notification.json, src/functionalTest/resources/scenarios/RIA-7948-internal-non-ada-submit-appeal-notification.json
RIA-TASK - Fix nightly functional tests.
=> RIA-TASK - Fix nightly functional tests.

charts/ia-case-notifications-api/Chart.yaml
https://tools.hmcts.net/jira/browse/DIAC-401
=> DIAC-401 bump chart version

src/main/resources/application.yaml
RIA-8913 - Updates to enable HO bail events for HO POU users
RIA-8913 - Updates to enable HO bail events for HO POU users
=> RIA-8913 - Updates to enable HO bail events for HO POU users

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepRemissionPaymentReminderPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepRemissionPaymentReminderPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8064
Telephony Payment - Payment reminder - LR Notification (Email) -Update
=> RIA-8064 record remission decision rejected fix

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeManageFeeUpdateAdditionalPaymentPersonalisation.java
https://tools.hmcts.net/jira/browse/RIA-8299
Fixing sonar issues that are blocking base PR building
=> RIA-8064 fix sonar cloud issues

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipRemissionRequestAutomaticReminderEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipRemissionRequestAutomaticReminderSms.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AiPRemissionRequestAutomaticReminderEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AiPRemissionRequestAutomaticReminderSmsTest.java
Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8061
Change description
Payment Reminder - AiP Notification (Email/SMS)
=> RIA-8061 - Payment Reminder - AiP Notification - fixing rejected

charts/ia-case-notifications-api/Chart.yaml
Bump charts version
Some of the template versions/names were straightened out in the 5.2.1 release. We're hoping this will help fix https://tools.hmcts.net/jira/browse/DIAC-401
=> DIAC-401 Update Chart Version

src/functionalTest/resources/scenarios/RIA-8857-aip-case-listed-notification-with-non-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-aip-case-listed-notification-with-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-aip-edit-case-listing-notification-with-non-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-aip-edit-case-listing-notification-with-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-case-listed-notification-with-non-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-case-listed-notification-with-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-edit-case-listing-notification-with-non-remote-hearing-refdata-enabled.json, src/functionalTest/resources/scenarios/RIA-8857-edit-case-listing-notification-with-remote-hearing-refdata-enabled.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinder.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-8857
Appeals Notifications displays the correct ref data location information
- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] tests have been updated / new tests has been added (if needed)
=> RIA-8857 - Appeals Notifications displays the correct ref data location information

src/functionalTest/resources/scenarios/RIA-8301-internal-api-submit-appeal-with-fee-out-of-time-letter-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8301
Appeal submitted out of time with fee letter
=> RIA-8301 appeal submitted out of time with fee letter

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOnTimeWithFeePersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/AppellantInternalCaseSubmittedOnTimeWithFeePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisationTest.java
[RIA-8298] Paper appeal submitted on time with fee to pay- Non Detained (by post) notification - HMCTS JIRA
Updating fields for fee in internal journey
=> RIA-8298 and 8301 - updating new fee fields

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/RecordApplicationRespondentFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/EmailAddressFinder.java
https://tools.hmcts.net/jira/browse/RIA-8839
=> RIA-8839 Refactor the handling of 'decisionWithoutHearing' appeals

src/functionalTest/resources/scenarios/RIA-8300-internal-aip-submit-appeal-out-of-time-with-exemption-letter-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithExemptionLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithExemptionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8300
- Letter generation sent for Submit Appeal - Internal - Out of time - With exemption (RP/DC appeals)
=> RIA-8300 Internal letter for submit appeal out of time with exemption

src/functionalTest/resources/scenarios/RIA-8320-internal-non-detained-manage-fee-update.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/FeeUpdateReason.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/FeeUpdateReasons.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeDirectedToReviewAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalManageFeeUpdateLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithRemissionLetterPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOnTimeWithFeePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeDirectedToReviewAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalManageFeeUpdateLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8320
Appeal fee changed(Additional payment required) - Non Detained (by post) notification
=> RIA-8320 letter notification internal update fee

src/functionalTest/resources/scenarios/RIA-8337-internal-aip-end-appeal-letter-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java
https://tools.hmcts.net/jira/browse/RIA-8337
- Letter bundle notification (bundle pdf stored in caseData) sent to appellant filtered by documentTag
=> RIA-8337 Internal end appeal letter bundle notification

src/functionalTest/resources/scenarios/RIA-8345-internal-aip-end-appeal-automatically-letter-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseEndAppealAutomaticallyLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseEndAppealAutomaticallyLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8345
- Letter generation through GovNotify template for End Appeal Automatically event triggered after 14 days of non-payment for appeal types with a fee
=> RIA-8345 Internal appellant end appeal automatically letter

src/functionalTest/resources/scenarios/RIA-4929-hearing-bundle-is-ready-notification.json
https://tools.hmcts.net/jira/browse/DIAC-380
=> DIAC-380 fix post notification template change

src/functionalTest/resources/scenarios/RIA-8305-internal-aip-case-listed-letter-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java
https://tools.hmcts.net/jira/browse/RIA-8305
Change description
Case listed - Non Detained (by post) notification
=> RIA-8305 - Case listed - Non Detained (by post) notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithRemissionLetterPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithRemissionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8302
Paper appeal submitted late with remission request- Non Detained (by post) notification
=> RIA-8302 appeal submitted late with remission

src/functionalTest/resources/scenarios/RIA-8339-internal-aip-reinstate-appeal-letter-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8339-internal-aip-reinstate-appeal-letter-notification-out-of-country.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalReinstateAppealLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalReinstateAppealLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8339
- Letter notification for Internal non-detained cases triggered by Reinstate Appeal event
- Covers both in-country and out-of-country scenarios
- Unit and functional tests
=> RIA-8339 Internal letter notification for Reinstate Appeal

src/functionalTest/resources/scenarios/RIA-8669-mark-appeal-as-remitted-non-detained-appellant-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMarkAppealAsRemittedNonDetainedPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMarkAppealAsRemittedNonDetainedPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMarkAppealAsRemittedNonDetainedPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMarkAppealAsRemittedNonDetainedPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-8668
RIA-8668 Add new notifications for MarkAppealAsRemitted when case is internal and in country
=> RIA-8668 Add new notifications for MarkAppealAsRemitted when case is internal and in country

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-9172
- Adding a new check for Appellant address in-country and out of country field
=> RIA-9172 OOC end appeal changes

src/functionalTest/resources/scenarios/RIA-4929-hearing-bundle-is-ready-notification.json, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/controllers/AsylumPreSubmitCallbackControllerTest.java
Empty commit to trigger build on DLRM-refund
=> RIA-1111 empty_commit_retrigger_build

src/functionalTest/resources/scenarios/RIA-8333-internal-case-disposed-under-rule-31-in-country-letter.json, src/functionalTest/resources/scenarios/RIA-8333-internal-case-disposed-under-rule-31-out-of-country-letter.json, src/functionalTest/resources/scenarios/RIA-8333-internal-case-disposed-under-rule-32-in-country-letter.json, src/functionalTest/resources/scenarios/RIA-8333-internal-case-disposed-under-rule-32-out-of-country-letter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseDisposeUnderRule31Or32Personalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseDisposeUnderRule31Or32PersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8333
Internal letter(by post) for FTPA disposed of under rules 31 or 32 - Non Detained &OOC
=> RIA-8333 disposal_under_31_32

src/functionalTest/resources/scenarios/RIA-9173-internal-aip-submit-appeal-with-exemption-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithExemptionLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithExemptionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9173
- Sending letter notification for OOC scenario for Submit Appeal with fee exemption
- Updated unit tests and FTs
=> RIA-9173 Adding OOC scenario for internal submit appeal with exemption

src/functionalTest/resources/scenarios/RIA-9174-internal-aip-submit-appeal-out-of-time-with-exemption-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseDisposeUnderRule31Or32Personalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithExemptionLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithExemptionLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeApplyForFtpaNonDetainedAndOutOfCountryPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalLateRemissionRejectedLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalMarkAsRemittedLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalReinstateAppealLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRemissionPartiallyGrantedOrRejectedLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithExemptionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9174
- Enabling OOC scenario for Submit Appeal Out of Time letter notification
- Updated unit and functional tests
=> RIA-9174 Enabling OOC scenario for submit appeal OOC and out of time

src/functionalTest/resources/scenarios/RIA-9176-generate-hearing-bundle-in-country-non-detained-notification.json, src/functionalTest/resources/scenarios/RIA-9176-generate-hearing-bundle-out-of-country-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeGenerateHearingBundlePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeGenerateHearingBundlePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9176
RIA-9176 Create Generate hearing bundle HO notification for internal cases
=> RIA-9176 Create Generate hearing bundle HO notification for internal cases

build.gradle
=> DIAC-000 - fix: get participantVersion from GIT_COMMIT env var

src/functionalTest/resources/scenarios/RIA-9162-internal-aip-submit-appeal-out-of-time-with-remission-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithRemissionLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealOutOfTimeWithRemissionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9162
- Enabling OOC scenario to send letter notification for Submit appeal out of time with remission
=> RIA-9162 OOC scenario for submit appeal out of time with remission letter

src/functionalTest/resources/scenarios/RIA-9163-internal-aip-submit-appeal-with-remission-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithRemissionLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithRemissionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9163
- Enabling OOC scenario for Submit Appeal in time with remission letter notification
=> RIA-9163 OOC scenario for submit appeal in time with remission letter notification

src/functionalTest/resources/scenarios/RIA-9164-internal-aip-submit-appeal-with-fee-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOnTimeWithFeePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOnTimeWithFeePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9164
- Enabling OOC scenario for submit appeal on time with fee to pay letter notification
=> RIA-9164 OOC submit appeal in time with fee out letter notification

src/functionalTest/resources/scenarios/RIA-8338-internal-edit-appeal-post-submit-letter-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8338-internal-edit-appeal-post-submit-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalEditAppealPostSubmitLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalEditAppealPostSubmitLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8338
Internal letter notification for edit appeal post submit
=> RIA-8338 Internal letter notification for edit appeal post submit

src/functionalTest/resources/scenarios/RIA-8340-internal-decided-without-hearing-notification.json, src/functionalTest/resources/scenarios/RIA-9166-internal-decided-without-hearing-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseDecisionWithoutHearingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseDecisionWithoutHearingPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9167
Decision without hearing OOC letter
=> RIA-9166 Decision no hearing OOC letter

src/functionalTest/resources/scenarios/RIA-9168-internal-aip-submit-appeal-with-fee-out-of-time-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9168
- Enabling OOC scenario for Submit Appeal out of time with fee letter notification
=> RIA-9168 OOC scenario for submit appeal out of time with fee letter

src/functionalTest/resources/scenarios/RIA-9179-ftpa-internal-in-country-applicant-appeal-decision-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-9179-ftpa-internal-out-of-country-applicant-appeal-decision-granted-respondent.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerFtpaDecisionRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerFtpaDecisionRespondentPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9179
RIA-9179 Add ftpa decission granted admin notification for internal cases
=> RIA-9179 Add ftpa decission granted admin notification for internal cases

src/functionalTest/resources/scenarios/RIA-9180-ftpa-internal-in-country-applicant-appeal-decision-partially-granted-respondent.json, src/functionalTest/resources/scenarios/RIA-9180-ftpa-internal-out-of-country-applicant-appeal-decision-partially-granted-respondent.json
https://tools.hmcts.net/jira/browse/RIA-9180
RIA-9180 Add FTPA application partially granted for internal cases
=> RIA-9180 Add FTPA application partially granted for internal cases

src/functionalTest/resources/scenarios/RIA-8720-internal-aip-late-remission-request-rejected-in-country.json, src/functionalTest/resources/scenarios/RIA-8720-internal-aip-late-remission-request-rejected-out-of-country.json
https://tools.hmcts.net/jira/browse/RIA-8720
Updating functional tests that were disabled
=> RIA-8720  Remission refused - functional test fix

src/functionalTest/resources/scenarios/RIA-8305-internal-aip-case-listed-letter-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8305-internal-aip-case-listed-letter-notification-oot.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-9171
Added FT for OOT case for listing event and edited NotificationHandlerConfiguration conditions on this event.
=>  RIA-9171 add_ft_and_oot_conditions

src/functionalTest/resources/scenarios/RIA-9165-internal-non-detained-manage-fee-update-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalManageFeeUpdateLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmittedOutOfTimeWithFeePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalManageFeeUpdateLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9165
- Enabling OOC scenario for Manage Fee Update event letter notification
=> RIA-9165 OOC scenario for manage fee update letter notification

src/functionalTest/resources/scenarios/RIA-8304-internal-ho-direction-to-review-the-appeal-appellant-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8304-internal-ho-direction-to-review-the-appeal-appellant-notification-out-of-country.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeDirectedToReviewAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeDirectedToReviewAppealPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9170
Added OOC scenario to internal request respondent review
=> RIA-9170 Added OOC scenario to internal request respondent review

src/functionalTest/resources/scenarios/RIA-9169-internal-ho-directed-to-upload-hearing-bundle-letter-notification-ooc.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeDirectedToUploadBundleLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalHomeOfficeDirectedToUploadBundleLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9169
This notification is sent when a LO directs the HO to upload the bundle. Appellant OOC
=> RIA-9169 HO directed to upload bundle OOC

src/functionalTest/resources/scenarios/RIA-8329-internal-aip-edit-case-listing-letter-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8329-internal-aip-edit-case-listing-letter-notification-out-of-country.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java
=> RIA-8329 Send letter bundle in the notification when 'Edit Case Listing' is complete

src/functionalTest/resources/scenarios/RIA-8334-update-tribunal-decision-r31-internal-letter-notification-in-country-decision.json, src/functionalTest/resources/scenarios/RIA-8334-update-tribunal-decision-r31-internal-letter-notification-ooc-decision.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalUpdateTribunalDecisionRule31LetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalUpdateTribunalDecisionRule31LetterPersonalisationTest.java
- When the decision is changed under Rule 31.
=>  RIA-8334 Send letter notification to the appellant when the event 'Update Tribunal Decision' is completed

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8307
Updated configuration to fix notifications
=> RIA-8307 Updated configuration to fix notifications

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-9165
- Bug fix, using absolute value for fee difference ignoring negatives.
=> RIA-9165 Bug fix, using absolute value for fee difference to avoid negatives

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-9130
RIA-9130 Make Update Tribunal decision event available to LO
=> RIA-9130 Make Update Tribunal decision event available to LO

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailHearingCentre.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailHearingCentreTest.java
https://tools.hmcts.net/jira/browse/DIAC-550
=> DIAC-550 replacing yarlswood with yarlsWood to fix issues

src/functionalTest/resources/scenarios/RIA-9154-internal-api-progress-migrated-case-with-fee-letter-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-9154
Update PROGRESS_MIGRATED_CASE to send a Notification
=> RIA-9154 - Update PROGRESS_MIGRATED_CASE to send a Notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGenerator.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGeneratorTest.java
https://tools.hmcts.net/jira/browse/RIA-9288
=> RIA-9288 - Update to send aip email when is remote hearing is updated

build.gradle, config/owasp/suppressions.xml
[DIAC-556](https://tools.hmcts.net/jira/browse/DIAC-556)
Remove deprecated JCenter
=> DIAC-556 Remove JCenter

src/functionalTest/resources/scenarios/RIA-9218-legalrep-refund-confirmation-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepRefundConfirmationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepRefundConfirmationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9218
Added Notification to LR with payment instructions for a second payment because of full refund. Added junit and Ft tests.
=> RIA-9218 add_notification_to_lr_for_second_payment

build.gradle
=> DIAC-527 - fix null GIT_COMMIT env variable

src/functionalTest/resources/scenarios/RIA-9217-aip-appellant-refund-confirmation-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantRefundConfirmationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantRefundConfirmationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantRefundConfirmationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantRefundConfirmationPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-9217
- Email + SMS notifications to AIP Appellant when Refund Confirmation event is triggered
- Unit + functional tests
=> RIA-9217 Refund confirmation notifications AIP

src/functionalTest/resources/scenarios/RIA-8224-update-tribunal-decision-rule31-notification.json, src/functionalTest/resources/scenarios/RIA-8224-update-tribunal-decision-rule32-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUpdateTribunalDecisionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamUpdateTribunalDecisionPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-8224
Update Tribunal decision - Detained Non ADA notification
=> RIA-8224 Update Tribunal decision - Detained Non ADA notification

src/functionalTest/resources/scenarios/RIA-8249-internal-detained-manage-fee-update.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamManageFeeUpdatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamManageFeeUpdatePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8250
https://tools.hmcts.net/jira/browse/RIA-8249
Email notification that includes embedded letter for manage a fee update for appellant's in detention.
- [x ] tests have been updated / new tests has been added (if needed)
=> RIA-8250 RIA-8249 Email notification and letter for manage a fee update for detained

src/functionalTest/resources/scenarios/RIA-8719-internal-aip-late-remission-decision-approved-out-of-country.json, src/functionalTest/resources/scenarios/RIA-9349-internal-aip-late-remission-decision-partially-approved-in-country.json, src/functionalTest/resources/scenarios/RIA-9349-internal-aip-late-remission-decision-partially-approved-out-of-country.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalLateRemissionPartiallyOrGrantedLetterPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalLateRemissionPartiallyOrGrantedLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9349
- Added separate letter to be sent for when remission decision is partially approved after the fee has been paid.
- [x ] tests have been updated / new tests has been added (if needed)
=> RIA-9349 Adding partially granted late remission decision after paid letter

build.gradle, gradle/wrapper/gradle-wrapper.properties
See [RIA-9525](https://tools.hmcts.net/jira/browse/RIA-9525)
RIA-9525 Fix libraries
=> RIA-9525 Fix libraries

src/functionalTest/resources/scenarios/RIA-3453-make-an-application-notification-judge-review-after-listing.json, src/functionalTest/resources/scenarios/RIA-3453-make-an-application-notification-judge-review-before-listing.json
=> DIAC-123 functional update after template subject change

src/functionalTest/resources/scenarios/RIA-3453-make-an-application-notification-judge-review-after-listing.json, src/functionalTest/resources/scenarios/RIA-3453-make-an-application-notification-judge-review-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantManageFeeUpdatePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantManageFeeUpdatePersonalisationEmailTest.java
See [RIA-9553](https://tools.hmcts.net/jira/browse/RIA-9553)
RIA-9553 Use previous amount while sending mange a fee update notification
=> RIA-9553 Use previous amount while sending mange a fee update notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java
See [RIA-9553](https://tools.hmcts.net/jira/browse/RIA-9553)
RIA-9553 Remove legal rep notification introduced wrongly
=> RIA-9553 Remove legal rep notification introduced wrongly

src/functionalTest/resources/scenarios/RIA-8246-legal-rep-manage-fee-additional-payment-requested-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeManageFeeUpdateAdditionalPaymentPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeManageFeeUpdateAdditionalPaymentPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9559
Added flag to LegalRepresentativeManageFeeUpdateAdditionalPaymentPersonalisation, edited FT and junit tests.
=> RIA-9559 add_flag_to_notification

src/functionalTest/resources/scenarios/RIA-9560-manage-fee-update-aip-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantManageFeeUpdatePersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantManageFeeUpdatePersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantManageFeeUpdatePersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantManageFeeUpdatePersonalisationSmsTest.java
See [RIA-9525](https://tools.hmcts.net/jira/browse/RIA-9525)
=> RIA-9560 Disable additional payment notification

src/functionalTest/resources/scenarios/RIA-9562-aip-appellant-notifications-remission-decision-partially-approved.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantRecordRemissionDecisionPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantRecordRemissionDecisionPersonalisationSms.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantRecordRemissionDecisionPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AipAppellantRecordRemissionDecisionPersonalisationSmsTest.java
See [RIA-9562](https://tools.hmcts.net/jira/browse/RIA-9562)
RIA-9562 Disable additional payment notification
=> RIA-9562 Disable additional payment notification

src/functionalTest/resources/scenarios/RIA-9219-internal-appellant-in-country-refund-confirmation-letter.json, src/functionalTest/resources/scenarios/RIA-9219-internal-appellant-out-of-country-refund-confirmation-letter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRefundConfirmationLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRefundConfirmationLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-9219
Added Refund confirmation personalisation for Letter, FT, junit tests, updated configuration files
=> RIA-9219 refund_confirmation

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/utils/WhatHappensNextContentUtils.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRespondentApplicationDecidedLetterPersonalisationTest.java
=> RIA-1234 sonar_fixes_notifications

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/SendsDirectionTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/NotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/StoredNotification.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailEmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailSmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/LetterNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/SmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelper.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/StoredNotificationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelperTest.java
Reverts hmcts/ia-case-notifications-api#1338
=> DIAC-546 Revert "DIAC-546 - Revert "DIAC-546 - writing failed notifications to notifications tab""

src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/component/SendsDirectionTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/NotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/StoredNotification.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailEmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailSmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/LetterNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/SmsNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSender.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelper.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/StoredNotificationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/BailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EditListingEmailNotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationGeneratorTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/BailGovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/GovNotifyNotificationSenderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/clients/helper/NotificationSenderHelperTest.java
Reverts hmcts/ia-case-notifications-api#1342
=> DIAC-546 - Revert DIAC-546 - writing failed notifications to notifications tab

src/functionalTest/resources/scenarios/RIA-1976-RIA-2694-respondent-review-direction-birmingham.json, src/functionalTest/resources/scenarios/RIA-1976-RIA-2694-respondent-review-direction-glasgow.json, src/functionalTest/resources/scenarios/RIA-1976-RIA-2694-respondent-review-direction-hatton-cross.json, src/functionalTest/resources/scenarios/RIA-1976-RIA-2694-respondent-review-direction-north-shields.json, src/functionalTest/resources/scenarios/RIA-4626-send-respondent-review-direction-aip.json, src/functionalTest/resources/scenarios/RIA-722-RIA-2694-send-respondent-review-direction-manchester.json, src/functionalTest/resources/scenarios/RIA-722-RIA-2694-send-respondent-review-direction-taylor-house.json, src/main/resources/application.yaml
https://github.com/hmcts/ia-case-notifications-api/pull/1347
=> DIAC-871 AC4 and AC5 templates update

src/functionalTest/resources/scenarios/RIA-4690-request-response-amend-aip.json
=> DIAC-928 Func test disabled

README.md
=> DIAC-000 - Update README.md

build.gradle, config/owasp/suppressions.xml
See [DIAC-1377](https://tools.hmcts.net/jira/browse/DIAC-1377)
=> DIAC-1377non springboot 3 upgrade related cve fixes

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUploadRespondentEvidencePersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUploadRespondentEvidencePersonalisationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1253
=> DIAC-1253 Build case LR notification for detained appeal

src/functionalTest/resources/scenarios/DIAC-1277-force-case-to-submit-hearing-requirements.json, src/functionalTest/resources/scenarios/RIA-2776-force-case-to-submit-hearing-requirements.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeForceCaseToSubmitHearingRequirementsDetentionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeForceCaseToSubmitHearingRequirementsDetentionPersonalisationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1277
=> DIAC-1277 notification force case to submit hearing requirements lr detention

src/functionalTest/resources/scenarios/DIAC-1314-internal-aip-submit-appeal-out-of-time-with-fee-to-pay.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1314
Sending appellant appeal submission letter when detained in other facility and appeal 
late and there is a fee to pay
=> DIAC-1314 Sending appellant appeal submission letter when detained in other facility

src/functionalTest/resources/scenarios/DIAC-1325-internal-aip-submit-appeal-with-remission-letter-notification-detained-in-other.json, src/functionalTest/resources/scenarios/DIAC-1353-internal-ho-direction-to-review-the-appeal-appellant-notification-detained-other.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1353
DIAC-1353 HO directed to review the appeal - Detained (in Other) notification 
A FT has been included in this PR
=> DIAC-1353 HO directed to review the appeal - Detained (in Other) 

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
Removing incorrect and unnecessary brackets  
=> DIAC-0000 fixing bracket over excitement

src/functionalTest/resources/scenarios/DIAC-1331-internal-aip-record-remission-decision-letter-partially-granted-detained-in-other.json, src/functionalTest/resources/scenarios/DIAC-1331-internal-aip-record-remission-decision-letter-rejected-detained-in-other.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1331
Remission partially granted or refused - Detained (in Other) notification
=> DIAC-1331 Remission partially granted or refused - Detained (in Other) notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsDetainedPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealAsDetainedPersonalisationTest.java
Mark as detained event is failing on AIP digital appeals while sending HO notifications.
This PR is to handle missing AIP states while retrieving HO email addresses
=> DIAC-1231 Fix to handle AIP digital case states

src/functionalTest/resources/scenarios/DIAC-1332-internal-out-of-time-remission-granted-detained-in-other.json, src/functionalTest/resources/scenarios/RIA-8308-internal-out-of-time-remission-granted-detained-in-other.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRemissionGrantedInTimeLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRemissionGrantedOutOfTimeLetterPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRemissionGrantedInTimeLetterPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalRemissionGrantedOutOfTimeLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1332
Remission granted for appellant detained in other
=> DIAC-1332 Remission granted for appellant detained in other

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveDetentionStatusPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeRemoveDetentionStatusPersonalisationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1458
DIAC-1458 Detained AIP Case States Bug (Remove Detention Status)
This PR will be used by another ia-case-api PR for testing this
=> DIAC-1458 Detained AIP Case States Bug (Remove Detention Status)

src/functionalTest/resources/scenarios/DIAC-1370-internal-aip-reinstate-appeal-detained-in-other-letter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1370
Appeal reinstated- Detained (in Other) notification
=> DIAC-1370 Appeal reinstated- Detained (in Other) notification

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/DIAC-1359-internal-aip-decide-respondent-application-detained-in-other-letter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1359
HO application decided - Detained (in Other) notification
=> DIAC-1359 HO application decided - Detained (in Other) notification

src/functionalTest/resources/scenarios/DIAC-1253-request-case-building-detained-direction.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestCaseBuildingDetainedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestCaseBuildingDetainedPersonalisationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1253
=> DIAC-1253 Legalrep notification to build case

charts/ia-case-notifications-api/Chart.yaml, src/functionalTest/resources/scenarios/DIAC-1376-internal-detained-in-other-manage-fee-update.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1376
Appeal fee changed - Detained (in Other) notification
=> DIAC-1376 https://tools.hmcts.net/jira/browse/DIAC-1376

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java
Adding migrated to state enum.  Causing error when deserialising.
=> DIAC-0000 Adding migrated to state enum

config/owasp/suppressions.xml
=> DIAC-0000 Fix conflict

src/functionalTest/resources/scenarios/DIAC-1371-internal-aip-mark-appeal-remitted-letter-notification-detained-other.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml
See [DIAC-1371](https://tools.hmcts.net/jira/browse/DIAC-1371)
Appeal remitted form the UT/CoA - Detained (in Other) notification
=> DIAC-1371 Appeal remitted form the UT/CoA - Detained (in Other) notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealSubmittedLateWithExemptionPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppealSubmittedLateWithExemptionPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/DIAC-1311
Paper appeal submitted late with exemption - Detained (in IRC or Prison) notification
=> DIAC-1311 Paper appeal submitted late with exemption - Detained (in IRC or Prison) notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithExemptionLetterPersonalisation.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/letter/AppellantInternalCaseSubmitAppealWithExemptionLetterPersonalisationTest.java
https://tools.hmcts.net/jira/browse/DIAC-1324
DIAC-1324 fix to remove the duplicate template
=> DIAC-1324 fix to remove the duplicate template

src/functionalTest/resources/scenarios/RIA-6939-mark-appeal-as-detained.json, src/functionalTest/resources/scenarios/RIA-9525-mark-appeal-as-detained.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1440
DIAC-1440 Fix to handle LR manual notification
=> DIAC-1440 Fix to handle LR manual notification

src/main/resources/strings.tsv
https://tools.hmcts.net/jira/browse/DIAC-1441
DIAC-1441 Update Detention Location Name Correction
locsl testing
=> DIAC-1441 Update Detention Location Name Correction

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
See [DIAC-1426](https://tools.hmcts.net/jira/browse/DIAC-1426)
Fix to enable existing notifications for LR HO and LO for  Remove Legal Representative (Admin/LO)
=> DIAC-1426 Fix to enable existing notifications for LR HO and LO

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
=> DIAC-1305 fixing-handler-condition

src/functionalTest/resources/scenarios/DIAC-1441-update-detention-location-lr-manual-letter.json, src/functionalTest/resources/scenarios/RIA-9234-update-detention-location-legal-rep-notification-after-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeLetterUpdateDetentionLocationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateDetentionLocationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1232
DIAC-1232 fix to stop email notification for internal cases & log to investigate no notification scenarios
=> DIAC-1232 fix to stop email notification for internal cases & log to investigate no notification scenarios

src/functionalTest/resources/scenarios/DIAC-1378-internal-detained-out-of-time-decision-allowed.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetLateRemissionGrantedInPrisonOrIrcAipManualPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetLateRemissionGrantedInPrisonOrIrcAipManualPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
See [DIAC-1403](https://tools.hmcts.net/jira/browse/DIAC-1403)
Late remission request granted - Detained (in IRC or Prison) notification
=> DIAC-1403 Late remission request granted - Detained (in IRC or Prison) notification

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1380
=> DIAC-1380 HO directed to review the appeal - Detained (in IRC or Prison) notification

src/main/resources/strings.tsv
https://tools.hmcts.net/jira/browse/DIAC-1432
Udating IRC spelling
=> DIAC-1432 Udating IRC spelling

src/main/resources/strings.tsv
https://tools.hmcts.net/jira/browse/DIAC-1432
Correcting Hewell prison
=> DIAC-1432 Correcting hewell prison

charts/ia-case-notifications-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DIAC-1627
DIAC-1627 update pod config
=> DIAC-1627 update pod config
