hmcts/ia-case-notifications-api

build.gradle, infrastructure/main.tf
=> Upgraded tomcat in response to CVE-2019-0232, CVE-2019-0199

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/MultipleNotificationsTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/AppealSubmittedCaseOfficerNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeHearingRequirementsDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeReviewDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentNonStandardDirectionNotifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentReviewDirectionNotifier.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/AppealSubmittedCaseOfficerNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/BuildCaseDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeHearingRequirementsDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/LegalRepresentativeReviewDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentEvidenceDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentNonStandardDirectionNotifierTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/RespondentReviewDirectionNotifierTest.java
All notifications now call NotificationIdAppender to make ids unique
bumping spring version for CVE-2018-15756 and code some code tidy up
https://tools.hmcts.net/jira/browse/RIA-1394
see jira
```
[ ] Yes
[x] No
```
=> RIA-1394 sending multiple notifications

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationIdAppender.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationIdAppenderTest.java
Changing notification reference to use UUID instead of numbers.
=> Replacing number with UUID for notification references.

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/Parties.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DirectionTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/PartiesTest.java
Added appellant to the Parties enum and requestReasonsForAppeal to
DirectionTag enum as we are now sending a direction the respondent when
an aip case is sent to the respondent to review.
https://tools.hmcts.net/jira/browse/RIA-2866
```
[ ] Yes
[X] No
```
=> RIA-2866 TCW review reasons for appeal

src/functionalTest/resources/scenarios/RIA-893-RIA-1897-send-home-office-evidence-direction.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHomeOfficeBundlePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRequestHomeOfficeBundlePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-1897
- Added a new personalisation for legal rep which is sent when case officer requests the Home Office bundle from respondent.
- Updated functional test to reflect the changes.
```
[ ] Yes
[x] No
```
=> RIA-1897: Sending a notification to legal rep when case officer requests HO evidence

src/functionalTest/resources/scenarios/RIA-2959-adjourn-hearing-without-date.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAdjournHearingWithoutDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAdjournHearingWithoutDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAdjournHearingWithoutDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAdjournHearingWithoutDatePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-2959
- Added new personalisation for legal representative.
- Added new personalisation for case officer.
- Added new personalisation for admin officer.
- Added new personalisation for respondent.
- Added functional test to check that the correct notifications are sent with prepopullated values.
```
[ ] Yes
[x] No
```
=> RIA-2959: Notifications sent during adjourn hearing without date event.

src/functionalTest/resources/scenarios/RIA-2959-adjourn-hearing-without-date.json, src/functionalTest/resources/scenarios/RIA-2961-re-list-case-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerPersonalisationProvider.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReListCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAdjournHearingWithoutDatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/EmailNotificationGenerator.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerAdjournHearingWithoutDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerPersonalisationProviderTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerReListCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerAdjournHearingWithoutDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAdjournHearingWithoutDatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentAdjournHearingWithoutDatePersonalisationTest.java
…t. (#249)
* RIA-2959: Notifications sent during adjourn hearing without date event.
- Added new personalisation for legal representative.
- Added new personalisation for case officer.
- Added new personalisation for admin officer.
- Added new personalisation for respondent.
- Added functional test to check that the correct notifications are sent with prepopullated values.
* fix some issues from QA
* fix unit test
* fix unit test and check style
* bring up to date
* remove string
Co-authored-by: david.crespo <david.crespo@hmcts.net>
```
[ ] Yes
[ ] No
```
=> Adjourned without a date epic

build.gradle
[RIA-3370](https://tools.hmcts.net/jira/browse/RIA-3370)
Bumped jackson-datatype and jackson-databind from 2.10.1 to 2.11.1
```
[ ] Yes
[x] No
```
=> Bumped jackson-datatype and jackson-databind from 2.10.1 to 2.11.1

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerClarifyingQuestionsAnswersSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerFtpaDecisionHomeOfficeNotificationFailedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHomeOfficeResponseUploadedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCmaPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerManageFeeUpdatePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerReasonForAppealSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRequestHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRespondentEvidenceSubmittedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmitAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmitCasePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmittedHearingRequirementsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerUploadAddendumEvidencePersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerClarifyingQuestionsAnswersSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerFtpaDecisionHomeOfficeNotificationFailedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerHomeOfficeResponseUploadedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerListCmaPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerMakeAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerManageFeeUpdatePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerReasonForAppealSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRespondentEvidenceSubmittedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerResponseRequestHearingRequestPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmitAppealPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmitCasePersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerSubmittedHearingRequirementsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerUploadAddendumEvidencePersonalisationTest.java
[RIA-4748](https://tools.hmcts.net/jira/browse/RIA-4748)
Change the default value to true for the **tcw-notifications** LD feature flag. This will ensure that the notifications continue to go our in the event the flag is unavailable. This will also address the Nightly Build issue.
```
[ ] Yes
[x] No
```
=> Change default value for tcw-notifications feature flag

src/main/resources/application.yaml
[RIA-5747](https://tools.hmcts.net/jira/browse/RIA-5747)
- When admin triggers the RECORD_REMISSION_DECISION event && remission is REJECTED, an email notification is being sent to LR. It's now pointing to the [new template](https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/templates/bd1bc55d-cece-4aff-b38a-a72e506f662a) rather than the[ old template](https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/templates/8a48b422-c6ed-448d-aec0-a5b43bd2b472), instead of changing the old template directly. So that the new template will only be used by whatever environment the dev branch (ia-case-notifications-card-payments) is being promoted to.
- The old template can be archived when there'll no environment left using it
- AIP …
=> RIA-5747 Use a different template for remission rejected LR notification

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-1647-RIA-1276-RIA-2936-end-appeal-home-office-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-2239-RIA-2936-end-appeal-home-office-notification-judge-after-listing.json, src/functionalTest/resources/scenarios/RIA-4321-end-appeal-aip-notification-after-listing-CO.json, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-6121
This is to allow any home office user with home office bails to process bails notification events
```
[ ] Yes
[ x ] No
```
=> RIA-6121 Change HO permission roles for bail notification events v2

src/functionalTest/resources/scenarios/RIA-6608-ada-suitability-suitable.json, src/functionalTest/resources/scenarios/RIA-6609-ada-suitability-suitable.json, src/functionalTest/resources/scenarios/RIA-6609-ada-suitability-unsuitable.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AdaSuitabilityReviewDecision.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeAdaSuitabilityPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAdaSuitabilityPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeAdaSuitabilityPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeAdaSuitabilityPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6609
https://tools.hmcts.net/jira/browse/RIA-6608
Added ADA suitability notifications for suitable and unsuitable emails
TESTED output:
Unsuitable
(LR)
https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/notification/bdaee905-54f0-4df7-956c-721be2dae0c6
(HO)
https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/notification/dfdb04d4-c524-415d-b00e-c6d379f974b9
Suitable
(LR)
https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/notification/083a1f02-3739-435e-849b-135a9c8047a4
(HO)
https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/notification/3604a625-2eb1-4fe8-a026-1d86103ee809
**Does this PR introduce a breaking …
=> RIA-6609 Added ADA suitability notifications for suitable and unsuitable

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-6733
* A notification is currently being sent to Legal rep on 'markAppealPaid' event. 
* Since Internal cases have no legal representative, attempt to send notifications fail. 
* This ensures that such notification is sent only if the appeal is not internal case.
```
[ ] Yes
[x] No
```
=> RIA-6733: Make 'Mark appeal as paid' event available for internal cases

src/functionalTest/resources/scenarios/RIA-6811-internal-ada-case-decide-an-application-granted.json, src/functionalTest/resources/scenarios/RIA-6811-internal-ada-case-decide-an-application-refused.json, src/functionalTest/resources/scenarios/RIA-6811-internal-ada-case-decide-an-application.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/MakeAnApplicationType.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/MakeAnApplicationTypeTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamDecideAnApplicationPersonalisationTest.java
[RIA-6811](https://tools.hmcts.net/jira/browse/RIA-6811)
- Personalisation for DET for application decided when ADA internal case
- As can be seen from the [NotificationHandlerConfiguration](src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java) :
- if proper AIP journey (aip frontend):
- email sent as usual to appellant
- if not proper AIP journey (LR journey, aka non-aip frontend)
- if non internal: 
- if ADA: emails sent as usual to LR and HO
- if non-ADA: emails sent as usual to LR and HO
- if internal: 
- if ADA: email sent to DET
- if non-ADA: `not set`
```
[ ] Yes
[x] No
```
=> RIA-6811 Add Det personalisation, MakeAnApplicationType model, beans

src/functionalTest/resources/scenarios/RIA-6782-hearing-bundle-is-ready-notification-to-det-ada.json, src/functionalTest/resources/templates/minimal-internal-appeal-submitted.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHearingBundleReadyPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/TestUtils.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamHearingBundleReadyPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestResponseReviewPersonalisationTest.java
- Added personalisation to set the map for DET notification when ASYNC_STITCHING_COMPLETE is complete and status is DONE.
- Added a check to disable LR configuration when ASYNC_STITCHING_COMPLETE is complete for internal case.
- Tested the notifications for internal ADA appeal. two notifications sent out: *_HEARING_BUNDLE_IS_READY_DET_ADA_EMAIL and *_HEARING_BUNDLE_IS_READY_HOME_OFFICE
- Refactored methods in TestUtils to help getDocument or DocumentinList.
```
[ ] Yes
[x] No
```
=> RIA-6782: Enabled notification for DET when Hearing bundle is ready

charts/ia-case-notifications-api/Chart.yaml, src/functionalTest/resources/scenarios/RIA-6811-internal-ada-case-decide-an-application-applicant-granted.json, src/functionalTest/resources/scenarios/RIA-6811-internal-ada-case-decide-an-application-applicant-refused.json, src/functionalTest/resources/scenarios/RIA-6812-internal-ada-case-decide-an-application-other-granted.json, src/functionalTest/resources/scenarios/RIA-6812-internal-ada-case-decide-an-application-other-refused.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMakeAnApplicationPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMakeAnApplicationPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeMakeAnApplicationPersonalisationTest.java
[RIA-6920](https://tools.hmcts.net/jira/browse/RIA-6920)
- Added admin role to HO personalizations for `makeAnApplication` and `decideAnApplication`
- Made the LR personalization for `makeAnApplication` return an empty recipients list for an internal case (no LR email present) so that it doesn't throw an error
```
[ ] Yes
[x] No
```
=> Ria 6920 enable preexisting notifications

src/functionalTest/resources/scenarios/RIA-6781-internal-ada-case-ada-suitability-notification-suitable.json, src/functionalTest/resources/scenarios/RIA-6781-internal-ada-case-ada-suitability-notification-unsuitable.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAdaSuitabilityReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAdaSuitabilityReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6781
Added new yaml entry for DET internal ADA suitability template.
Added Ada Suitability and appeal form to DocumentTag.
Added bean for DET ADA Suitability notification generator and handler.
Modified existing ADA suitability bean in handler to prevent multiple notifs going out for LR created cases. Now it will only go out for LR created cases, whilst the functionality for internal cases has been implemented within this PR.
Added unit/functional tests.
Testing:
Submitted ADA suitability as judge for:
- Internal ADA case
- LR ADA case
Notifications are sent out as expected
```
[ ] Yes
[ ] No
```
=> Ria 6781 ada suitability review notification to DET - Unrepresented/internal cases

charts/ia-case-notifications-api/Chart.yaml, src/functionalTest/resources/scenarios/RIA-6803-ftpa-respondent-granted-internal-ada-case.json, src/functionalTest/resources/scenarios/RIA-6803-ftpa-respondent-partially-granted-internal-ada-case.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRespondentFtpaApplicationDecidedPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRespondentFtpaApplicationDecidedPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-6803
* Some refactoring
* Update handler to handle only currently implemented decision types when respondent ftpa application is decided for internal cases (granted, partially granted, refused, not admitted)
* Update existing personalisation to support 'granted' and 'partially granted' decision types.
```
[ ] Yes
[x] No
```
=> RIA-6803 HO's FTPA granted/partially granted notification

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeDecideAnApplicationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-6966
Changed the implementation of obtaining aria listing ref in HO personalisation
Testing:
LR Journey
Made an application with LR after listing and decided application with LO. Generated emails:
Email to law firm:
Email to HO:
Unrepresented journey. Generated emails:
Email to DET:
Email to HO:
```
[ ] Yes
[X] No
```
=> RIA-6696 HO decide an application not showing Aria Listing Ref

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7001
RIA-7001 Added isInternalCase check on appellant notifications for FTPA decision by judge. Affected beans are:
ftpaApplicationDecisionRefusedOrNotAdmittedAppellantNotificationHandler
ftpaApplicationDecisionGrantedOrPartiallyGrantedAppellantNotificationHandler
ftpaApplicationDecisionReheardAppellantNotificationHandler
Testing:
Created 4 unrep cases
Case 1 permission granted
case 2 permission partially granted
case 3 permission refused
case 4 application not permitted
```
[ ] Yes
[ ] No
```
=> RIA-7001 Unrep FTPA decision callback error - Appellant notif being sent causing event to fail

src/functionalTest/resources/scenarios/RIA-6112-ftpa-submitted-aip.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java
[RIA-6133](https://tools.hmcts.net/jira/browse/RIA-6133)
- Enabled existing AO and HO notifications to be triggered when a citizen triggers `APPLY_FOR_FTPA_APPELLANT` (in addition to the new appellant notification)
```
[ ] Yes
[x] No
```
=> RIA-6133 Enable existing notifications for AO and HO (AIP FTPA submitted)

src/functionalTest/resources/scenarios/RIA-6940-remove-detention-status-appellant-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-6940-remove-detention-status-appellant-notification-before-listing.json, src/functionalTest/resources/scenarios/RIA-6940-remove-detention-status-appellant-notification-email-only-after-listing.json, src/functionalTest/resources/scenarios/RIA-6940-remove-detention-status-appellant-notification-email-only-before-listing.json, src/functionalTest/resources/scenarios/RIA-6940-remove-detention-status-appellant-notification-sms-only.json, src/functionalTest/resources/scenarios/RIA-6940-remove-detention-status-no-appellant-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveDetainedStatusPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveDetainedStatusPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantRemoveDetainedStatusPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantRemoveDetainedStatusPersonalisationSmsTest.java
https://tools.hmcts.net/jira/browse/RIA-6940
Added email/sms notif to appellant for AIP journey when Admin triggers removeDetainedStatus.
Added Email/SMS personlisations
Added bean to notification handler/generator
Added unit/functional tests for personlisations
Testing:
SMS to appellant:
Before listing email to appellant:
After listing email to appellant:
When Email + SMS both chosen, 2 emails are sent out (HO/appellant) and 1 text.
When SMS chosen and Email is NOT chosen, 1 text is sent and 1 email (to HO) is sent.
When Email chosen and SMS is NOT chosen, only 2 emails sent (HO/appellant)
Tested scenario where mobile number and email address both NOT provided. No screenshots to attach but functional test for this scenario added. Works as expected (only HO notif sent, no appellant …
=> Ria 6940 remove detained status appellant notification (email/sms)

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-7030-reinstate-appeal-internal-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-7030-reinstate-appeal-internal-notification-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-7030
Added new notification handler/generator for internal cases where reinstate appeal event is triggered
Updated handler for normal (non aip non unrepped) cases to not trigger when case is unrepped
Updated yaml values for gov notify template IDs
```
[ ] Yes
[X] No
```
=> RIA-7030 reinstate appeal notification

src/functionalTest/resources/scenarios/RIA-6072-aip-make-an-application-notification-home-office-apc-after-listing.json, src/functionalTest/resources/scenarios/RIA-6072-aip-make-an-application-notification-home-office-apc-before-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/MakeAnApplicationTypes.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMakeAnApplicationPersonalisationEmail.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMakeAnApplicationPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/MakeAnApplicationService.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AppellantMakeAnApplicationPersonalisationEmailTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/sms/AppellantMakeAnApplicationPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/MakeAnApplicationServiceTest.java
[RIA-6948](https://tools.hmcts.net/jira/browse/RIA-6948)
- Add verbalization mapping for the `applicationType` variable used in AIP notifications for the `MAKE_AN_APPLICATION` event
```
[ ] Yes
[x] No
```
=> RIA-6948 MakeAnApplication notifications

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAppealReadyForUtTransferPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeMarkAsReadyForUtTransferPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-7392
- QA fix: Sending HO notification to same end appeal email address (before listing) or the HO hearing centre email (after listing)
- Existing LR and AiP internal flows remain unchanged
```
[ ] Yes
[X] No
```
=> RIA-7392 Refactor of HO notif. for Mark as UT event AiP Citizen

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateDetentionLocationPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeUpdateDetentionLocationPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7486
* Added subject prefix in personalisation
* Updated unit test
* Updated notification templates (acf67e1c-ec14-48f5-aed9-61a703831a5c and 59bbd0ed-2b2f-432b-8111-0cb4b9ea9a7d)
```
[ ] Yes
[X] No
```
=> RIA-7486 update detention location notification - incorrect subject on email

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/ia-case-notifications-api/Chart.yaml, charts/ia-case-notifications-api/values.yaml, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/ConfigValidatorAppListener.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/ConfigValidatorAppListenerTest.java
https://tools.hmcts.net/jira/browse/RIA-7383
Adding ia.config.validator.secret to application.yaml + ConfigValidatorAppListener to check to see if secrets are being applied by azure.
```
[ ] Yes
[x] No
```
=> RIA-7378 - preventing application startup if secrets can't be found

charts/ia-case-notifications-api/Chart.yaml, src/functionalTest/resources/scenarios/RIA-6779-internal-ada-case-request-respondent-evidence.json, src/functionalTest/resources/scenarios/RIA-7218-internal-non-ada-request-respondent-review-det-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRespondentReviewPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRespondentReviewPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7218
- Replaced check for ADA with check for in Detention to allow notification to send for both ADA and Detained Non-ADA
- Corrected a typo on notification tag 'DETENTION'
- Unit tests updated
- Functional test updates and new scenario for prison as detention facility
```
[ ] Yes
[X] No
```
=> RIA-7218 Non-ADA notification request respondent review

src/functionalTest/resources/scenarios/RIA-7152-internal-ada-request-case-building-colnbrook-notification.json, src/functionalTest/resources/scenarios/RIA-7152-internal-ada-request-case-building-tinsley-house-notification.json, src/functionalTest/resources/scenarios/RIA-7160-internal-detained-request-case-building-notifications-det-prison.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestCaseBuildingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamRequestCaseBuildingPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7160
- Rework the notification to DET for Request Case Building event to allow both ADA and Non-ADA templates (each has different number and name/links for forms)
- Fixed Subject prefix in pre-existing ADA notification to match what's in application.yaml and adjusted functional tests accordingly
- Some renaming of generator and handler which is reused for both, so made it more generic
```
[ ] Yes
[X] No
```
=> RIA-7160 request case building notifications DET non-ADA

src/functionalTest/resources/scenarios/RIA-7555-internal-detained-home-office-response-review-decision-maintained.json, src/functionalTest/resources/scenarios/RIA-7555-internal-detained-home-office-response-review-decision-withdrawn.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamReviewHomeOfficeResponsePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamReviewHomeOfficeResponsePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7555
* Adding functionality for generating notification when LO requests response review (for both decision maintained and wihdrawn)
* Added unit tests and FTs
* Updated DocumentTag
Email notification
Decision maintained letter
[maintained_letter.pdf](https://github.com/hmcts/ia-case-notifications-api/files/12359821/maintained_letter.pdf)
Decision withdrawn letter
[withdrawn_letter.pdf](https://github.com/hmcts/ia-case-notifications-api/files/12359839/withdrawn_letter.pdf)
```
[ ] Yes
[X] No
```
=> RIA-7555 review ho response notification (decision maintained + withdrawn)

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-2975-RIA-3003-ftpa-applicant-appeal-decision-not-admitted-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-3003-ftpa-applicant-appeal-decision-refused-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-3003-ftpa-applicant-appeal-decision-reheard-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-4352-ftpa-applicant-appeal-decision-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-2975-RIA-4352-ftpa-applicant-appeal-decision-partially-granted-appellant.json, src/functionalTest/resources/scenarios/RIA-3651-ftpa-applicant-appeal-decision-reheard-rule-32-appellant.json, src/functionalTest/resources/scenarios/RIA-3651-ftpa-applicant-appeal-decision-reheard-rule-35-appellant.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-appellant-not-admitted-in-country.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-appellant-partially-granted-out-of-country.json, src/functionalTest/resources/scenarios/RIA-6665-ftpa-appellant-refused-ada.json, src/functionalTest/resources/scenarios/RIA-7329-internal-appellant-ftpa-rj-decided-ada-granted.json, src/functionalTest/resources/scenarios/RIA-7329-internal-appellant-ftpa-rj-decided-ada-refused.json, src/functionalTest/resources/scenarios/RIA-7329-internal-appellant-ftpa-rj-decided-detained-non-ada-granted.json, src/functionalTest/resources/scenarios/RIA-7329-internal-appellant-ftpa-rj-decided-detained-non-ada-refused.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppellantFtpaDecidedByResidentJudgePersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppellantFtpaDecidedByResidentJudgePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7329
https://tools.hmcts.net/jira/browse/RIA-7676
RIA-7329
* Added notification template for residentJudgeFtpaDecision
* Created notification configurations for internal ADA and detained non-ADA cases when residentJudgeFtpaDecision is triggered for an FTPA that has been decided as granted, partially granted and refused only
* Imported doc tag
* Added unit and FTs
```
[ ] Yes
[X] No
```
=> RIA-7329 internal ADA/detained non-ada notification for residentJudgeFtpaDecision event when granted, partially granted or refused only

src/functionalTest/resources/scenarios/RIA-6803-ftpa-respondent-granted-internal-ada-case.json, src/functionalTest/resources/scenarios/RIA-6805-ftpa-respondent-not-addmitted-internal-ada-case.json, src/functionalTest/resources/scenarios/RIA-6805-ftpa-respondent-refused-internal-ada-case.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7359
https://tools.hmcts.net/jira/browse/RIA-7678
- Srihari found an issue where Respondent FTPA decisions were throwing an error trying to send a DET notification without document generated when triggering Leadership decision event. I removed the DET notification completely for this event as it is redundant (and this event will eventually be removed later down the line)
- Functional test fixes on which notifications to expect
```
[ ] Yes
[X] No
```
=> RIA-7359 RIA-7678 Fix for notifications using Leadership event

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppellantFtpaDecidedByResidentJudgePersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamAppellantFtpaDecidedByResidentJudgePersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7329
https://tools.hmcts.net/jira/browse/RIA-7676
* Refactored IAUT1 form link for template content. Unembedded link and seperated out the URL from the text.
```
[ ] Yes
[X] No
```
=> RIA-7329 RIA-7676 unembedded IAUT1 url from iaut1 text in template content

src/functionalTest/resources/scenarios/RIA-7691-internal-upload-addendum-evidence-admin-officer-det-notification-ada.json, src/functionalTest/resources/scenarios/RIA-7693-internal-upload-addendum-evidence-admin-officer-det-notification-non-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-7691 - ADA
https://tools.hmcts.net/jira/browse/RIA-7693 - Non-ADA
- Adding additional logic to only send notification when supplied by 'Appellant'. If 'Respondent' is selected then no notification is to be sent.
- Updated functional tests
=> RIA-7691 RIA-7693 Send notification only when supplied by appellant

src/functionalTest/resources/scenarios/RIA-7879-case-listed-notification-harmondsworth-hearing-centre.json, src/integrationTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/TsvStringProviderTest.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentre.java, src/main/resources/application.yaml, src/main/resources/strings.tsv, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/HearingCentreTest.java
https://tools.hmcts.net/jira/browse/RIA-7879
- Added the new hearing venue to location list
- Set the name and address for the new hearing venue
- Temporarily set the email address of home office and hearing centre for new hearing venue
```
[ ] Yes
[X] No
```
=> RIA-7879 map epims ids to ccd hearing locations

src/functionalTest/resources/scenarios/RIA-7443-internal-ada-legal-officer-upload-addendum-evidence-supplied-by-respondent-det-notification.json, src/functionalTest/resources/scenarios/RIA-7711-internal-detained-legal-officer-upload-addendum-evidence-supplied-by-respondent-det-notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentWithMetadata.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamLegalOfficerUploadAddendumEvidence.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamLegalOfficerUploadAddendumEvidenceTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-7443
https://tools.hmcts.net/jira/browse/RIA-7711
* Imported docTag from docs-api
* Added new template for LO upload addendum evidence supplied by Respondent
* Created new generator and handler beans for uploadAddendumEvidence event for internal detained cases
* Imported addendum evidence document extraction/parsing fom docs-api.
* Added/updated unit/FTs
=> RIA-7443 RIA-7711 internal LO upload addendum evidence supplied by respondent DET notification

src/functionalTest/resources/scenarios/RIA-7428-internal-reinstate-appeal-det-notification-ada.json, src/functionalTest/resources/scenarios/RIA-7712-internal-reinstate-appeal-det-notification-non-ada.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTag.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamReinstateAppealPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/DocumentTagTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/detentionengagementteam/DetentionEngagementTeamReinstateAppealPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7428 - ADA
https://tools.hmcts.net/jira/browse/RIA-7712 - Non-ADA
- New notification to DET for internal reinstate appeal scenarios, ADA and detained non-ADA.
- Maintain the HO notification and reuse notification handler but with the DET personalisation added to the generator.
- Unit and functional tests.
=> RIA-7428 RIA-7712 Notification for internal reinstate appeal

charts/ia-case-notifications-api/Chart.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/RIA-7991-record-adjournment-details.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerRecordAdjournmentDetailsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRecordAdjournmentDetailsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRecordAdjournmentDetailsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentRecordAdjournmentDetailsPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/adminofficer/AdminOfficerRecordAdjournmentDetailsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerRecordAdjournmentDetailsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/legalrepresentative/LegalRepresentativeRecordAdjournmentDetailsPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/respondent/RespondentRecordAdjournmentDetailsPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7791
- Added new email template for for CO, LR, AO and appellant when trigger recordAdjournmentDetails event
- Added the RecordAdjournmentDetailsPersonalisation for CO, LR, AO and appellant when trigger recordAdjournmentDetails event  with the condition "hearing could not be relisted right away"
- Added unit test and functional test for the notification of recordAdjournmentDetails event
- Updated the suppression list of CVE
- Updated the version of java helm chart to 5.0.0 from 4.0.13 because of pipeline failure
=> RIA-7791 Notice is sent when hearing is adjourned with no future hearing date

src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_ho_respond_to_costs_notification.json, src/functionalTest/resources/scenarios/RIA-7795-RIA-7796_legalrep_respond_to_costs_notification.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/RespondToCostsRespondentPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/RespondToCostsRespondentPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7795
Added Notification personalisation for respondent, when 'Respond to costs' event is triggered. Edited 7796 Ft tests. Added Junit tests. Fixed RespondToCostsApplicantPersonalisation.class typo in fields.
=> RIA-7795 respond_to_costs_respondent

src/functionalTest/resources/scenarios/RIA-2959-adjourn-hearing-without-date.json, src/functionalTest/resources/scenarios/RIA-7991-record-adjournment-details.json, src/functionalTest/resources/scenarios/RIA-8192-adjourn-hearing-without-date-list-assist-integrated.json, src/functionalTest/resources/scenarios/RIA-8192-record-adjournment-details-list-assist-integrated.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
[RIA-8192](https://tools.hmcts.net/jira/browse/RIA-8192)
- Made `adjournHearingWithoutDate` and `recordAdjournmentDetails` each be handled by an "integrated" handler and a "non-integrated" handler, so that the Admin notification generator is removed when the case is list assist integrated (`isIntegrated  =Yes`)
=> RIA-8192 No notifications for Admin in AdjournHearingWithoutDate and RecordAdjournmentDetails if isIntegrated

config/owasp/suppressions.xml, src/functionalTest/resources/scenarios/bail/RIA-8112-HO-upload-bail-summary-direction-notifications.json, src/functionalTest/resources/scenarios/bail/RIA-8349-RIA-8352-send-bail-initial-case-listing-notifications.json, src/functionalTest/resources/scenarios/bail/RIA-8349-RIA-8352-send-bail-relisting-case-listing-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailHearingLocation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ListingEvent.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/handlers/presubmit/NotificationHandler.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSms.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinder.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/BailNotificationHandlerConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailCaseDefinitionTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/BailHearingLocationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ListingEventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/applicant/sms/ApplicantBailCaseListingPersonalisationSmsTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/homeoffice/email/HomeOfficeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/bail/legalrepresentative/email/LegalRepresentativeBailCaseListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/HearingDetailsFinderTest.java
https://tools.hmcts.net/jira/browse/RIA-8349
https://tools.hmcts.net/jira/browse/RIA-8352
- Notification sent to HO, LR and Applicant (SMS) for Case Listing event: initial listing and relisting scenarios
- Initial listing also sends notification to HO to upload bail summary. Not for relisting.
- No LR? Only sent to HO and Applicant
- No applicant mobile number? Only sent to HO and LR
=> RIA-8349 RIA-8352 Bail case listing notifications

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsRespondentAndApplicantPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/applyforcosts/DecideCostsRespondentAndApplicantPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-7810
Decision notifications should send to both applicant and respondent (LR and HO) even if no responses are given.
- [ x] README and other documentation has been updated / added (if needed)
=> RIA-7810 - Decision notifications should send to both LR and HO

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/RIA-8230
Refactor of this logic to prevent IndexOutOFBounds Exception when completedStages is not present (or empty) since this screen is removed as part of DLRM. This allows the event to be submitted successfully.
=> RIA-8230 Refactor to enable scenario with no completedStages

build.gradle
Done in order for mutations to pass as they dropped to 89 after multiple releases
=> DIAC-123 dropping mutation threshhold to 85

build.gradle, config/owasp/suppressions.xml
[DIAC-374](https://tools.hmcts.net/jira/browse/DIAC-374)
[DIAC-372](https://tools.hmcts.net/jira/browse/DIAC-372)
[DIAC-370](https://tools.hmcts.net/jira/browse/DIAC-370)
[DIAC-371](https://tools.hmcts.net/jira/browse/DIAC-371)
Update uk.gov.service.notify:notifications-java-client:3.19.2-RELEASE to version 5.0.0 fixing CVE-2023-5072.
Update bouncy castle to bcprov-jdk18on v1.75 and exclude older bouncy castle modules from dependencies fixing CVE-2023-33202.
Remove unnecessary suppressions.
=> DIAC-366 CVEs

src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerEditListingPersonalisation.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingPersonalisation.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/caseofficer/CaseOfficerEditListingPersonalisationTest.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/homeoffice/HomeOfficeEditListingPersonalisationTest.java
https://tools.hmcts.net/jira/browse/RIA-8944
- set the hearingCentreAddress to "remote hearing" when the value of "listCaseHearingCentre" is remote hearing
- update unit test
- this PR will affect two email template only ([LO email: "513c5d12-7e26-4430-8560-d3a42a2d5df0"](https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/templates/513c5d12-7e26-4430-8560-d3a42a2d5df0) and [HO email: "071cc334-89f7-4bce-bf88-637057f4811a"](https://www.notifications.service.gov.uk/services/7f72d0fb-2bc4-421b-bceb-1bf5bf350ff9/templates/071cc334-89f7-4bce-bf88-637057f4811a))
=> RIA-8944 fix the incorrect email notification triggered for LO and HO

src/functionalTest/resources/scenarios/RIA-9217-aip-appellant-in-country-refund-confirmation-notifications.json, src/functionalTest/resources/scenarios/RIA-9217-aip-appellant-out-of-country-refund-confirmation-notifications.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantRefundConfirmationPersonalisationEmail.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/personalisation/appellant/email/AipAppellantRefundConfirmationPersonalisationEmailTest.java
https://tools.hmcts.net/jira/browse/RIA-9217
- While testing OOC scenario on Preview, I realise I needed a new template to remove Home Office reference number from the header as this field is not present for AIP OOC cases. Have implemented this now.
- New functional test scenario for OOC added
=> RIA-9217 OOC email template scenario added

src/functionalTest/resources/scenarios/RIA-7030-reinstate-appeal-internal-notification-after-listing.json, src/functionalTest/resources/scenarios/RIA-7030-reinstate-appeal-internal-notification-before-listing.json, src/functionalTest/resources/scenarios/RIA-7417_appeal_edited_ada_notification.json, src/functionalTest/resources/scenarios/RIA-7428-internal-reinstate-appeal-det-notification-ada.json, src/functionalTest/resources/scenarios/RIA-7691-internal-upload-addendum-evidence-admin-officer-det-notification-ada.json, src/functionalTest/resources/scenarios/RIA-7693-internal-upload-addendum-evidence-admin-officer-det-notification-non-ada.json, src/functionalTest/resources/scenarios/RIA-7707_appeal_edited_non-ada_notification.json, src/functionalTest/resources/scenarios/RIA-7712-internal-reinstate-appeal-det-notification-non-ada.json, src/functionalTest/resources/scenarios/RIA-8338-internal-edit-appeal-post-submit-letter-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8338-internal-edit-appeal-post-submit-letter-notification-ooc.json, src/functionalTest/resources/scenarios/RIA-8339-internal-aip-reinstate-appeal-letter-notification-in-country.json, src/functionalTest/resources/scenarios/RIA-8339-internal-aip-reinstate-appeal-letter-notification-out-of-country.json, src/functionalTest/resources/scenarios/RIA-9187-non-standard-in-country-non-detained-send-direction-hearing-requirements-after-listing.json, src/functionalTest/resources/scenarios/RIA-9187-non-standard-out-of-country-send-direction-after-listing.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/utils/AsylumCaseUtils.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/AsylumCaseUtilsTest.java
https://tools.hmcts.net/jira/browse/RIA-9460
When on ICC journey admin choosed that applicant will represent himself, then triggered submit and then editAppealAfterSubmit it throwed an error, because it could not retrieve any of existing LegalRep emails. Now in this particular situation when "It is internal journey and appellant represents himself we return empty string.
=> RIA-9460 bug_fix

src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/util/MapFieldAssertor.java, src/functionalTest/java/uk/gov/hmcts/reform/iacasenotificationsapi/verifiers/NotificationVerifier.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationIdAppender.java, src/test/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/service/NotificationIdAppenderTest.java
https://tools.hmcts.net/jira/browse/DIAC-835
Add timestamp to the sentNotifictaions data to filter downloadable notifications in saveNotificationsData event.
=> DIAC-835 Add timestamp to the sentNotifications

src/functionalTest/resources/scenarios/DIAC-1360-internal-decided-without-hearing-notification-detained-in-other.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1360
Decision without a hearing - Detained (in Other) notification
=> DIAC-1360 Decision without a hearing - Detained (in Other) notification

src/functionalTest/resources/scenarios/DIAC-1356-internal-case-disposed-under-rule-31-in-detained-in-other.json, src/functionalTest/resources/scenarios/DIAC-1356-internal-case-disposed-under-rule-32-detained-in-other-letter.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1356
FTPA disposed of under rules 31 or 32 - Detained (in Other) notification
=> DIAC-1356 FTPA disposed of under rules 31 or 32 - Detained (in Other) notification

src/functionalTest/resources/scenarios/DIAC-1339-edit-case-listing-notification-harmondsworth-hearing-centre.json, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/domain/entities/AsylumCaseDefinition.java, src/main/java/uk/gov/hmcts/reform/iacasenotificationsapi/infrastructure/config/NotificationHandlerConfiguration.java
https://tools.hmcts.net/jira/browse/DIAC-1341
DIAC-1341 Cancellation of Production Notice Detained - shouldTriggerReviewInterpreterTaskcondition added to editCaseListingProduction and hearingCancelledProduction. In hearingCancelledProduction asylumBeforeCase now used to compare if In Person and listCaseHearingDateBefore condition added
This will be tested in Preview
=> DIAC-1341 Cancellation of Production Notice Detained 7
